//! `extern "C"` shim codegen for classes (DESIGN §6.2, §6.5).
//!
//! Mirrors the `bffi-macros` build policy: debug builds run the body
//! bare (a panic aborts), release builds wrap it in
//! `::bffi_core::boundary::run_extern_body`. Every shim validates the
//! incoming handle through the `ObjectWrap`/Registry barriers (tag +
//! generation + null) before any use.
//!
//! The transport-level token generators (out-parameters, return tails,
//! cstring conversions, small type renderers) live in
//! `crate::support::codegen`; this module assembles them into the
//! class-specific shims.
//!
//! Generated code never `expect`s or `panic!`s: a tag collision is
//! stored as the sticky `ObjectWrap` init outcome and surfaces as a
//! runtime error code - user crates compile under the same
//! `-D warnings` lints as the framework.

use crate::class::mapping::ShimKind;
use crate::class::model::{ClassModel, ConstructorModel, FieldTy, ImplModel, MethodModel};
use crate::support::codegen::{
    bigint_ty, out_param, param_conversions, param_ident, prim_ty, ret_body, shim_param,
};
use crate::support::paths::PathCtx;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// The generated wrap-accessor identifier for a class.
pub(crate) fn wrap_ident(js_name: &str) -> proc_macro2::Ident {
    format_ident!("__bffi_{js_name}_wrap")
}

/// The match arm for an `Err(ObjectError)`: store, convert, return
/// the code. Inlined at every site so neither expansion depends on
/// the other's generated items; diverges with `return`, so it fits
/// both value positions and nested matches.
fn error_arm(ctx: &PathCtx) -> TokenStream {
    let _ = ctx;
    quote! {
        {
            let converted: ::bffi::BffiError = ::std::convert::Into::into(error);
            let code = converted.status_u32();
            ::bffi::set_last_error(converted);
            return code;
        }
    }
}

/// Renders the `#[bffi_class]` expansion tail: the wrap accessor plus
/// the release and field-getter shims.
pub(crate) fn class_shims(model: &ClassModel) -> TokenStream {
    let paths = &model.paths;
    let core = &paths.core;
    let object = &paths.object;
    let wrap_fn = wrap_ident(&model.js_name);
    let struct_ident = &model.ident;
    // Interpolated as a plain hex literal; the u16 conversion happens
    // at the call site (`TypeTag(<lit>)`).
    let tag_lit = syn::LitInt::new(
        &format!("{:#06x}", model.tag),
        proc_macro2::Span::call_site(),
    );
    let release_ident = format_ident!("bffi_{}_release", model.js_name);
    let release_doc = format!(
        "Releases the `{}` instance handle (generated by `#[bffi_class]`).",
        model.js_name
    );
    let getters = model.fields.iter().map(|field| field_getter(model, field));
    let release = shim_pair(
        paths,
        &release_ident,
        &release_doc,
        quote! { handle: u64 },
        release_body(paths, &wrap_fn),
    );

    quote! {
        /// Wrap accessor generated by `#[bffi_class]`: the
        /// process-wide ObjectWrap for this type, claimed once. A tag
        /// collision stays sticky in the init result and surfaces as
        /// an error code on every call.
        fn #wrap_fn()
            -> ::std::result::Result<&'static #object::ObjectWrap<#struct_ident>, #object::ObjectError>
        {
            static WRAP: ::std::sync::OnceLock<
                ::std::result::Result<#object::ObjectWrap<#struct_ident>, #object::ObjectError>,
            > = ::std::sync::OnceLock::new();
            match WRAP.get_or_init(|| #object::ObjectWrap::new(#core::TypeTag(#tag_lit))) {
                ::std::result::Result::Ok(wrap) => ::std::result::Result::Ok(wrap),
                ::std::result::Result::Err(error) => ::std::result::Result::Err(*error),
            }
        }

        #(#getters)*

        #release
    }
}

/// The release transport body shared by both cfg variants.
fn release_body(ctx: &PathCtx, wrap_fn: &proc_macro2::Ident) -> TokenStream {
    let core = &ctx.core;
    let error_arm = error_arm(ctx);
    quote! {
        match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.release(#core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(_arc) => #core::ErrorCode::Ok.as_u32(),
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        }
    }
}

/// Renders one field-getter shim pair.
fn field_getter(model: &ClassModel, field: &crate::class::model::FieldModel) -> TokenStream {
    let core = &model.paths.core;
    let getter_ident = format_ident!("bffi_{}_{}_get", model.js_name, field.name);
    let field_ident = format_ident!("{}", field.name);
    let getter_doc = format!(
        "Reads the `{}` field of a `{}` instance (generated by `#[bffi_class]`).",
        field.name, model.js_name
    );
    let out_ty = match field.ty {
        FieldTy::Prim(prim) => prim_ty(prim),
        FieldTy::BigInt(big) => bigint_ty(big),
    };
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm(&model.paths);
    let body = quote! {
        if __ret.is_null() {
            let error = #core::BffiError::new(
                #core::ErrorCode::NullPointer,
                "output pointer is null",
            );
            #core::set_last_error(error);
            return #core::ErrorCode::NullPointer.as_u32();
        }
        let __arc = match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.get(#core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(arc) => arc,
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        };
        // SAFETY: `__ret` is non-null (checked above) and valid for one
        // write per the bun:ffi out-parameter contract.
        unsafe { ::std::ptr::write(__ret, __arc.#field_ident); }
        #core::ErrorCode::Ok.as_u32()
    };
    shim_pair(
        &model.paths,
        &getter_ident,
        &getter_doc,
        quote! { handle: u64, __ret: *mut #out_ty },
        body,
    )
}

/// Renders the `#[bffi_impl]` expansion tail: the constructor and
/// method shims.
pub(crate) fn impl_shims(model: &ImplModel) -> TokenStream {
    let ctor = constructor_shim(model);
    let methods = model
        .methods
        .iter()
        .map(|method| method_shim(model, method));

    quote! {
        #ctor

        #(#methods)*
    }
}

/// Renders the constructor shim: runs the Rust constructor, wraps the
/// value, writes the handle.
fn constructor_shim(model: &ImplModel) -> TokenStream {
    let core = &model.paths.core;
    let ctor: &ConstructorModel = &model.constructor;
    let shim_ident = format_ident!("bffi_{}_new", model.js_name);
    let shim_doc = format!(
        "Creates a `{}` instance and returns its handle (generated by `#[bffi_impl]`).",
        model.js_name
    );
    let type_ident = &model.type_ident;
    let ctor_ident = &ctor.ident;
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm(&model.paths);
    let params: Vec<TokenStream> = ctor
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| shim_param(&param.name, param.kind.clone(), index))
        .collect();
    let args = ctor.params.iter().enumerate().map(|(index, param)| {
        let name = param_ident(&param.name, index);
        match &param.kind {
            ShimKind::Str => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            // `ZeroCopyBuf` derefs to `[u8]`.
            ShimKind::BufferView => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            ShimKind::Prim(_) | ShimKind::BigInt(_) => quote! { #name },
            ShimKind::Record(_) | ShimKind::Seq(_) | ShimKind::Opt(_) => quote! { #name },
        }
    });
    let conversion = param_conversions(
        &model.paths,
        ctor.params
            .iter()
            .map(|param| (param.name.as_str(), param.kind.clone())),
    );
    let body = quote! {
        if __ret.is_null() {
            let error = #core::BffiError::new(
                #core::ErrorCode::NullPointer,
                "output pointer is null",
            );
            #core::set_last_error(error);
            return #core::ErrorCode::NullPointer.as_u32();
        }
        #conversion
        let __value = #type_ident::#ctor_ident(#(#args,)*);
        match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.wrap(__value) {
                    ::std::result::Result::Ok(handle) => {
                        // SAFETY: `__ret` is non-null (checked above) and valid
                        // for one `u64` write per the bun:ffi out-parameter contract.
                        unsafe { ::std::ptr::write(__ret, handle.as_u64()); }
                        #core::ErrorCode::Ok.as_u32()
                    }
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        }
    };
    shim_pair(
        &model.paths,
        &shim_ident,
        &shim_doc,
        quote! { #(#params,)* __ret: *mut u64 },
        body,
    )
}

/// Renders one `&self` method shim pair.
fn method_shim(model: &ImplModel, method: &MethodModel) -> TokenStream {
    let core = &model.paths.core;
    let shim_ident = format_ident!("bffi_{}_{}", model.js_name, method.ident);
    let shim_doc = format!(
        "Calls `{}::{}` on the instance behind the handle (generated by `#[bffi_impl]`).",
        model.type_ident, method.ident
    );
    let type_ident = &model.type_ident;
    let method_ident = &method.ident;
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm(&model.paths);
    let params: Vec<TokenStream> = method
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| shim_param(&param.name, param.kind.clone(), index))
        .collect();
    let out = out_param(&method.ret);
    let args = method.params.iter().enumerate().map(|(index, param)| {
        let name = param_ident(&param.name, index);
        match &param.kind {
            ShimKind::Str => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            // `ZeroCopyBuf` derefs to `[u8]`.
            ShimKind::BufferView => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            ShimKind::Prim(_) | ShimKind::BigInt(_) => quote! { #name },
            ShimKind::Record(_) | ShimKind::Seq(_) | ShimKind::Opt(_) => quote! { #name },
        }
    });
    let conversion = param_conversions(
        &model.paths,
        method
            .params
            .iter()
            .map(|param| (param.name.as_str(), param.kind.clone())),
    );
    let call = quote! { #type_ident::#method_ident(&__arc, #(#args,)*) };
    let transport = ret_body(&model.paths, &method.ret, call);
    let body = quote! {
        #conversion
        let __arc = match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.get(#core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(arc) => arc,
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        };
        #transport
    };
    shim_pair(
        &model.paths,
        &shim_ident,
        &shim_doc,
        quote! { handle: u64, #(#params,)* #(#out)* },
        body,
    )
}

/// Renders both cfg variants of one shim symbol.
fn shim_pair(
    ctx: &PathCtx,
    ident: &proc_macro2::Ident,
    doc: &str,
    params: TokenStream,
    body: TokenStream,
) -> TokenStream {
    let core = &ctx.core;
    let debug_shim = quote! {
        #[cfg(debug_assertions)]
        #[unsafe(no_mangle)]
        #[doc = #doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #ident(#params) -> u32 {
            #body
        }
    };
    let release_shim = quote! {
        #[cfg(not(debug_assertions))]
        #[unsafe(no_mangle)]
        #[doc = #doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #ident(#params) -> u32 {
            #core::boundary::run_extern_body_u32(move || { #body })
        }
    };
    quote! { #debug_shim #release_shim }
}
