// @generated by bffi codegen - do not edit.
// Source module: workers
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  makeTakeError,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "workers",
  "functions": [
    {
      "name": "bind_js_thread",
      "export": "bffi_bind_js_thread",
      "docs": [
        "Registers the CURRENT thread as a JS thread of this process",
        "(multi-isolate: the main script and every Worker call this once on",
        "their own thread; idempotent; the registration dies with the",
        "thread). Returns the raw `ErrorCode` numeric value (`0` = bound)."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "unbind_js_thread",
      "export": "bffi_unbind_js_thread",
      "docs": [
        "Deregisters the CURRENT thread: the explicit shutdown half of",
        "[`bind_js_thread`]. A Worker calls this right before exiting so",
        "its slot queue retires immediately and further targeted deliveries",
        "to it fail fast (LoopStopped) instead of timing out. Idempotent."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "sum_to",
      "export": "bffi_sum_to",
      "docs": [
        "CPU-bound native work: sums `1..=n`. Callable from BOTH isolates",
        "concurrently - the reason a worker exists."
      ],
      "params": [
        {
          "name": "n",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "callback_register",
      "export": "bffi_callback_register",
      "docs": [
        "Registers a native doubling callback `i32(i32)`; the JS side",
        "invokes it by handle (kept from the callbacks example so the",
        "workers test can pin the JS -> Rust direction too)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "spawn_invoke_wait",
      "export": "bffi_spawn_invoke_wait",
      "docs": [
        "Spawns a DETACHED native thread that marshals the JS-bound",
        "callback behind `handle` with `invoke_wait(handle, [a], timeout)`:",
        "the job is delivered to the callback's OWNING isolate (the thread",
        "that bound it), never across an isolate boundary. The outcome",
        "lands in the process-wide slots ([`wait_code`] / [`wait_value`])."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "a",
          "ts": "number",
          "abi": "i32"
        },
        {
          "name": "timeout_ms",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "wait_code",
      "export": "bffi_wait_code",
      "docs": [
        "The code of the last `spawn_invoke_wait` outcome",
        "([`WAIT_PENDING`] = the detached thread has not reported yet)."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "wait_value",
      "export": "bffi_wait_value",
      "docs": [
        "The value delivered by the last successful outcome (`0` before)."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "i32"
      },
      "out": "i32"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "The non-blocking drain: a JS isolate calls this on its own ticks",
        "to execute queued jobs (its slot queue first, then the global",
        "queue). Returns the number of jobs executed by THIS call."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_bind_js_thread = new Uint32Array(1);
  const sym_bind_js_thread = sym("bffi_bind_js_thread");
  const fn_bind_js_thread = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("bind_js_thread: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_bind_js_thread(out_bind_js_thread));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_bind_js_thread failed: " + String(status));
    }
    return (out_bind_js_thread[0] ?? 0);
  };
  const out_unbind_js_thread = new Uint32Array(1);
  const sym_unbind_js_thread = sym("bffi_unbind_js_thread");
  const fn_unbind_js_thread = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("unbind_js_thread: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_unbind_js_thread(out_unbind_js_thread));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_unbind_js_thread failed: " + String(status));
    }
    return (out_unbind_js_thread[0] ?? 0);
  };
  const out_sum_to = new BigUint64Array(1);
  const sym_sum_to = sym("bffi_sum_to");
  const fn_sum_to = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("sum_to: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_sum_to(a0, out_sum_to));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_sum_to failed: " + String(status));
    }
    return (out_sum_to[0] ?? 0n);
  };
  const out_callback_register = new BigUint64Array(1);
  const sym_callback_register = sym("bffi_callback_register");
  const fn_callback_register = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("callback_register: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_callback_register(out_callback_register));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_callback_register failed: " + String(status));
    }
    return (out_callback_register[0] ?? 0n);
  };
  const sym_spawn_invoke_wait = sym("bffi_spawn_invoke_wait");
  const fn_spawn_invoke_wait = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>, a2: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 3) {
      throw new Error("spawn_invoke_wait: expected 3 argument(s), got " + arguments.length);
    }
    const status = Number(sym_spawn_invoke_wait(a0, a1, a2));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_spawn_invoke_wait failed: " + String(status));
    }
  };
  const out_wait_code = new Uint32Array(1);
  const sym_wait_code = sym("bffi_wait_code");
  const fn_wait_code = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("wait_code: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_wait_code(out_wait_code));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_wait_code failed: " + String(status));
    }
    return (out_wait_code[0] ?? 0);
  };
  const out_wait_value = new Int32Array(1);
  const sym_wait_value = sym("bffi_wait_value");
  const fn_wait_value = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("wait_value: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_wait_value(out_wait_value));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_wait_value failed: " + String(status));
    }
    return (out_wait_value[0] ?? 0);
  };
  const out_loop_pump = new BigUint64Array(1);
  const sym_loop_pump = sym("bffi_loop_pump");
  const fn_loop_pump = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pump: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pump(out_loop_pump));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pump failed: " + String(status));
    }
    return (out_loop_pump[0] ?? 0n);
  };
  return {
    "bind_js_thread": fn_bind_js_thread,
    "unbind_js_thread": fn_unbind_js_thread,
    "sum_to": fn_sum_to,
    "callback_register": fn_callback_register,
    "spawn_invoke_wait": fn_spawn_invoke_wait,
    "wait_code": fn_wait_code,
    "wait_value": fn_wait_value,
    "loop_pump": fn_loop_pump,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
