// @generated by bffi-dts - do not edit.
// Source module: b1

/** A point in 2D space. */
export interface Point {
  /** The x coordinate. */
  x: number;
  y: number;
}

/** The status of a job. */
export type JobStatus = "Idle" | "Running" | "Done";

/** Builds a point. */
export function make_point(x: number, y: number): Point;

/** All the points. */
export function all_points(): Point[];
