// @generated by bffi-dts - do not edit.
// Source module: streams

/** A numeric sequence. */
export function numbers(): AsyncIterableIterator<number>;

/** Record streams carry their composite item type. */
export function samples(): AsyncIterableIterator<Sample>;
