/**
 * Tests for the loader-schema renderer (`@z2net/bffi`'s generation
 * core): renderer determinism, the committed golden (regenerate with
 * BFFI_CODEGEN_OVERWRITE=1), canonicalization (key order does not
 * matter), and schema diagnostics.
 *
 * Run with `bun test packages/bffi`.
 */
import { describe, expect, test } from "bun:test";

import { renderModule } from "../src/codegen/generate.ts";
import { SchemaValidationError } from "../src/codegen/schema.ts";
const FIXTURE = {
  bffi: 1,
  module: "api",
  functions: [
    {
      name: "add",
      export: "bffi_add",
      docs: ["Adds two numbers."],
      params: [
        { name: "a", ts: "number", abi: "u32" },
        { name: "b", ts: "number", abi: "u32" },
      ],
      ret: { ts: "number", abi: "u32" },
      out: "u32",
    },
    {
      name: "shout",
      export: "bffi_shout",
      docs: [],
      params: [{ name: "name", ts: "string", abi: "cstring" }],
      ret: { ts: "string", abi: "buffer" },
      out: "handle",
    },
    {
      name: "compute",
      export: "bffi_compute",
      docs: ["Async compute."],
      params: [{ name: "x", ts: "number", abi: "u32" }],
      ret: { ts: "Promise<number>", abi: "task" },
      out: "handle",
    },
  ],
  classes: [
    {
      name: "counter",
      release: "bffi_counter_release",
      docs: ["A native counter."],
      constructor: {
        name: "constructor",
        export: "bffi_counter_new",
        docs: ["Creates a counter."],
        params: [{ name: "start", ts: "number", abi: "u32" }],
        ret: { ts: "bigint", abi: "handle" },
        out: "handle",
      },
      fields: [
        {
          name: "value",
          export: "bffi_counter_value_get",
          docs: ["The current value."],
          ts: "number",
          out: "u32",
        },
      ],
      methods: [
        {
          name: "increment",
          export: "bffi_counter_increment",
          docs: [],
          params: [],
          ret: { ts: "number", abi: "u32" },
          out: "u32",
        },
      ],
    },
  ],
};

describe("renderModule", () => {
  test("is deterministic and keeps the format contract", () => {
    const first = renderModule(FIXTURE);
    const second = renderModule(FIXTURE);
    expect(first).toBe(second);
    expect(first.startsWith("// @generated by bffi codegen - do not edit.\n")).toBeTrue();
    expect(first).toContain("// Source module: api\n");
    expect(first.endsWith(";\n")).toBeTrue();
    expect(first.includes("\r")).toBeFalse();
  });

  test("embeds the schema and the runtime import", () => {
    const rendered = renderModule(FIXTURE);
    expect(rendered).toContain('import { dlopen } from "bun:ffi";');
    expect(rendered).toContain('} from "@z2net/bffi";');
    expect(rendered).toContain("const moduleJson = {");
    expect(rendered).toContain("as const satisfies ModuleJson;");
    expect(rendered).toContain("export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson>");
    expect(rendered).toContain("export type Api = ReturnType<typeof createApiFromJson>;");
  });

  test("specializes wrappers: hoisted slots and symbols, exact arity", () => {
    const rendered = renderModule(FIXTURE);
    // The out slot and the symbol are hoisted to factory scope.
    expect(rendered).toContain("const out_add = new Uint32Array(1);");
    expect(rendered).toContain('const sym_add = sym("bffi_add");');
    // Exact positional parameters annotated through TsOf.
    expect(rendered).toContain('a0: TsOf<"number", typeof moduleJson>');
    // The arity check is exact.
    expect(rendered).toContain('if (arguments.length !== 2) {');
    // Task returns wrap through the runtime.
    expect(rendered).toContain('wrapTask(lib, (out_compute[0] ?? 0n), "Promise<number>", moduleJson) as unknown as TsOf<"Promise<number>", typeof moduleJson>');
    // Classes: the constructor writes this.handle (no value return).
    expect(rendered).toContain("      this.handle = (out_counter_constructor[0] ?? 0n);");
    expect(rendered.includes("return (out_counter_constructor")).toBeFalse();
  });

  test("the --runtime override changes the import specifier", () => {
    const rendered = renderModule(FIXTURE, "../bffi-loader/src/index.ts");
    expect(rendered).toContain('from "../bffi-loader/src/index.ts"');
  });

  test("canonicalizes key order", () => {
    const shuffled = {
      classes: FIXTURE.classes.map((cls) => ({
        methods: cls.methods,
        fields: cls.fields,
        constructor: cls.constructor,
        docs: cls.docs,
        release: cls.release,
        name: cls.name,
      })),
      functions: FIXTURE.functions.toReversed(),
      module: FIXTURE.module,
      bffi: FIXTURE.bffi,
    };
    // Only KEY order is canonicalized: the same ARRAY order with
    // restored key order must render identically.
    const sameOrder = {
      bffi: shuffled.bffi,
      module: shuffled.module,
      functions: shuffled.functions,
      classes: shuffled.classes,
    };
    expect(renderModule(shuffled)).toBe(renderModule(sameOrder));
  });

  test("canonicalizes abiVersion/exportsHash into the module header", () => {
    const rendered = renderModule(FIXTURE);
    // The fixture carries no abiVersion: canonicalization adds the
    // default; exportsHash stays absent.
    expect(rendered).toContain('"module": "api",\n  "abiVersion": 1,\n  "functions"');
    expect(rendered).not.toContain("exportsHash");
    const withMeta = renderModule({ ...FIXTURE, abiVersion: 1, exportsHash: "123" });
    expect(withMeta).toContain('"abiVersion": 1,\n  "exportsHash": "123",\n  "functions"');
  });

  test("documents createApiFromJson as the explicit low-level loader", () => {
    const rendered = renderModule(FIXTURE);
    expect(rendered).toContain("explicit low-level");
  });

  test("rejects unknown schema versions with a diagnostic", () => {
    expect(() => renderModule({ ...FIXTURE, bffi: 2 })).toThrow(SchemaValidationError);
    try {
      renderModule({ ...FIXTURE, bffi: 2 });
    } catch (error) {
      expect((error as SchemaValidationError).issues[0]?.path).toBe("$.bffi");
    }
  });

  test("rejects unknown abi names", () => {
    const broken: unknown = structuredClone(FIXTURE);
    const fn0 = (broken as typeof FIXTURE).functions[0];
    const param0 = fn0?.params[0];
    if (param0) {
      param0.abi = "int";
    }
    expect(() => renderModule(broken)).toThrow(/unknown name "int"/);
  });

  test("accepts the errors table with codes and payload fields", () => {
    const withErrors = {
      ...FIXTURE,
      errors: [
        {
          name: "UsersError",
          docs: ["The typed errors."],
          variants: [
            {
              name: "NotFound",
              docs: [],
              code: "0x1001",
              fields: [{ name: "id", docs: [], ts: "bigint" }],
            },
            { name: "InvalidAge", docs: [], code: "0x1002", fields: [] },
          ],
        },
      ],
    };
    const rendered = renderModule(withErrors);
    expect(rendered).toContain('"code": "0x1001"');
    expect(rendered).toContain('"errors"');
  });

  test("rejects error codes outside the reserved user range", () => {
    const bad = {
      ...FIXTURE,
      errors: [
        {
          name: "UsersError",
          docs: [],
          variants: [{ name: "NotFound", docs: [], code: "0x0042", fields: [] }],
        },
      ],
    };
    try {
      renderModule(bad);
      throw new Error("must have thrown");
    } catch (error) {
      expect(error).toBeInstanceOf(SchemaValidationError);
      const issue = (error as SchemaValidationError).issues[0];
      expect(issue?.path).toBe("$.errors[0].variants[0].code");
    }
  });
});

// ---------------------------------------------------------------------------
// Golden
// ---------------------------------------------------------------------------

const GOLDEN_PATH = new URL("./testdata/golden.gen.ts", import.meta.url);

describe("golden", () => {
  // The committed golden imports the runtime by its package name -
  // the same specifier a consumer's generated file carries.
  const rendered = renderModule(FIXTURE);

  /** Regenerates the committed golden (like `TRYBUILD=overwrite`):
   * `BFFI_CODEGEN_OVERWRITE=1 bun test packages/bffi`; re-run the
   * plain suite afterwards and review the diff by hand. */
  test("golden matches the committed file", async () => {
    if (process.env.BFFI_CODEGEN_OVERWRITE === "1") {
      await Bun.write(GOLDEN_PATH, rendered);
    }
    const committed = await Bun.file(GOLDEN_PATH).text();
    expect(rendered).toBe(committed.replace(/\r\n/g, "\n"));
  });
});
