/**
 * Tests for `bffi build`: the fail-fast config error, and the
 * `--skip-build` path (loader JSON -> codegen -> resolution -> dlopen
 * probe) against a scaffolded project with a BROKEN fake artifact -
 * the pipeline must surface the failure with exit 2, and the
 * generation step must have (re)written `api.gen.ts` on the way.
 * A real end-to-end build lives in the examples repo.
 *
 * Run with `bun test packages/bffi-cli`.
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { $ } from "bun";

const ROOT = `${import.meta.dir}/tmp/build`;
const BFFI_DIR = `${ROOT}/.bffi`;

const VALID_CONFIG = {
  bffi: 1,
  version: "0.1.0",
  module: "demo",
  crate: { dir: "crate", name: "bffi-demo", binary: "bffi_demo" },
};

const VALID_LOADER_JSON = JSON.stringify({
  bffi: 1,
  module: "demo",
  functions: [],
  classes: [],
});

async function scaffoldProject(): Promise<void> {
  await Bun.write(`${BFFI_DIR}/bffi.json`, `${JSON.stringify(VALID_CONFIG, null, 2)}\n`);
  await Bun.write(`${BFFI_DIR}/bffi.api.json`, VALID_LOADER_JSON);
  // A broken fake artifact at the resolved local path (platform-aware):
  // the dlopen probe must fail on it.
  const ext = process.platform === "win32" ? "dll" : process.platform === "darwin" ? "dylib" : "so";
  const prefix = process.platform === "win32" ? "" : "lib";
  await Bun.write(`${ROOT}/crate/target/release/${prefix}bffi_demo.${ext}`, new Uint8Array([1]));
}

describe("bffi build", () => {
  beforeAll(async () => {
    await scaffoldProject();
  });

  test("build fails fast on a missing config (exit 2)", () => {
    const { code, stderr } = runCli([
      "build",
      "--config",
      `${ROOT}/.bffi/does-not-exist.json`,
    ]);
    expect(code).toBe(2);
    expect(stderr).toContain("build failed");
  });

  test("build --skip-build surfaces the broken artifact (exit 2)", async () => {
    await $`rm -rf ${BFFI_DIR}/api.gen.ts`;
    const { code, stderr } = runCli([
      "build",
      "--config",
      `${BFFI_DIR}/bffi.json`,
      "--skip-build",
    ]);
    expect(code).toBe(2);
    expect(stderr).toContain("build failed");
    // The generation step ran before the resolution failure: the
    // generated module exists again, rendered from the loader JSON.
    const generated = await Bun.file(`${BFFI_DIR}/api.gen.ts`).text();
    expect(generated).toContain("@generated by bffi codegen");
  }, 15000);

  afterAll(async () => {
    await $`rm -rf ${ROOT}`;
  });
});

function runCli(args: string[]): { code: number; stdout: string; stderr: string } {
  const entry = `${import.meta.dir}/../bin/bffi.ts`;
  const proc = Bun.spawnSync(["bun", entry, ...args]);
  return {
    code: proc.exitCode,
    stdout: proc.stdout.toString(),
    stderr: proc.stderr.toString(),
  };
}
