//! The declarative generator of the JS-facing stream exports.
//!
//! [`bffi_stream_abi!`] expands - in the USER crate, not here - into
//! the two exports JavaScript needs to drive pull-chunk streams:
//! `bffi_stream_next` and `bffi_stream_drop`. Expansion must happen
//! in the user crate (the linker may drop unused `#[no_mangle]`
//! symbols from rlib dependencies); this mirrors
//! [`bffi_async_abi!`](crate::bffi_async::abi).
//!
//! | Symbol | Signature | Returns |
//! | --- | --- | --- |
//! | `bffi_stream_next` | `(handle: u64, max: u32, __ret: *mut u64) -> u32` | the `ErrorCode` numeric value; `__ret` receives the chunk's transient-buffer handle (`0` = exhausted) |
//! | `bffi_stream_drop` | `(handle: u64) -> u32` | `0` = dropped, `4` = unknown/stale handle |

// Internal module aliases (the pre-merge crate names).
use crate::bffi_build;
use crate::bffi_core;
use crate::bffi_types;
use crate::bffi_types::wire as wire_codec;

use super::Chunk;

/// Pulls one chunk and stores it as a `TAG_SEQ` transient buffer;
/// writes the buffer handle (or `0` for an exhausted stream) into
/// `ret` and returns the exported [`bffi::core::ErrorCode`] numeric
/// value.
///
/// # Safety
///
/// `ret` must be a valid pointer to one writable `u64` (the bun:ffi
/// out-parameter contract); the pointer is null-checked before the
/// write.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn next_as_code(handle: u64, max: u32, ret: *mut u64) -> u32 {
    if ret.is_null() {
        return bffi_core::ErrorCode::NullPointer.as_u32();
    }
    let outcome = super::next_chunk(bffi_core::Handle::from_raw(handle), max as usize);
    let written: Result<u64, bffi_core::BffiError> = match outcome {
        Ok(Chunk::Done) => Ok(0),
        Ok(Chunk::Items(items)) => {
            let mut payload = Vec::new();
            wire_codec::encode_seq_header(&mut payload, items.len());
            for item in &items {
                payload.extend_from_slice(item);
            }
            match bffi_build::runtime::store_bytes(bffi_types::CopiedBuf::from_vec(payload)) {
                Ok(buffer) => Ok(buffer.as_u64()),
                Err(error) => Err(bffi_core::BffiError::from(error)),
            }
        }
        Err(error) => Err(error.into()),
    };
    match written {
        Ok(handle_value) => {
            // SAFETY: `ret` is non-null (checked above) and valid for
            // one `u64` write per the bun:ffi out-parameter contract.
            unsafe { ::std::ptr::write(ret, handle_value) };
            bffi_core::ErrorCode::Ok.as_u32()
        }
        Err(error) => {
            let code = error.code;
            bffi_core::set_last_error(error);
            code.as_u32()
        }
    }
}

/// Drops the stream and returns the exported
/// [`bffi::core::ErrorCode`] numeric value (`0` = dropped, `4` =
/// unknown/stale handle).
#[must_use]
pub fn drop_as_code(handle: u64) -> u32 {
    if super::drop_stream(bffi_core::Handle::from_raw(handle)) {
        bffi_core::ErrorCode::Ok.as_u32()
    } else {
        bffi_core::ErrorCode::InvalidHandle.as_u32()
    }
}

/// Generates the two JS-facing stream exports.
///
/// Call once, at the root of the cdylib crate (next to
/// `bffi::bffi_runtime_abi!()` and `bffi::bffi_async_abi!()`).
///
/// | Symbol | Signature | Returns |
/// | --- | --- | --- |
/// | `bffi_stream_next` | `(handle: u64, max: u32, __ret: *mut u64) -> u32` | the `ErrorCode` numeric value; `__ret` receives the chunk's transient-buffer handle (`0` = exhausted) |
/// | `bffi_stream_drop` | `(handle: u64) -> u32` | `0` = dropped, `4` = unknown/stale handle |
#[macro_export]
macro_rules! bffi_stream_abi {
    () => {
        /// C ABI export generated by `bffi_stream_abi!()`: pulls up
        /// to `max` items as one `TAG_SEQ` transient buffer (`0`
        /// handle = exhausted).
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_stream_next(handle: u64, max: u32, __ret: *mut u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::bffi_stream::abi::next_as_code(handle, max, __ret)
            }
            #[cfg(not(debug_assertions))]
            {
                $crate::bffi_core::boundary::run_extern_body_or(
                    || $crate::bffi_stream::abi::next_as_code(handle, max, __ret),
                    $crate::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }

        /// C ABI export generated by `bffi_stream_abi!()`: releases
        /// a stream early.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_stream_drop(handle: u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::bffi_stream::abi::drop_as_code(handle)
            }
            #[cfg(not(debug_assertions))]
            {
                $crate::bffi_core::boundary::run_extern_body_or(
                    || $crate::bffi_stream::abi::drop_as_code(handle),
                    $crate::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }
    };
}
