//! # bffi-stream
//!
//! Streams over user iterators and producers (B2): a
//! `#[bffi_stream]` export hands JavaScript a stream handle; the
//! generic `bffi_stream_next` export pulls chunks. The items are
//! pre-encoded wire records (`Vec<u8>` of one complete
//! `[tag][payload]` each), so the chunk crosses as one `TAG_SEQ`
//! payload through the ordinary transient-buffer channel - no new
//! ABI shapes.
//!
//! Two models share one table and one pull ABI:
//!
//! - **pull** (B2.1): the entry holds a user iterator; `next` runs
//!   it on the JS thread under the entry mutex (the iterator must
//!   not block indefinitely);
//! - **push** (B2.2): the entry holds a bounded buffer fed by a
//!   producer future running on the async executor
//!   ([`Ctx::push`](Ctx::push) parks with backpressure when the
//!   buffer is full). An empty live buffer reports
//!   [`StreamError::Pending`] - not an error, a retry hint: the JS
//!   wrapper waits a tick and pulls again (the same explicit-drain
//!   philosophy as `pumpUntil`; the buffer is shared memory, so the
//!   pull IS the delivery).
//!
//! A panic inside a pull iterator poisons that stream only
//! (`catch_unwind` marks the entry errored; the table survives).
//! Dropping a stream marks it done; a producer pushing afterwards
//! sees [`StreamError::Closed`] and its future ends.
//!
//! The stream table reuses the global [`Registry`] under tag
//! `0x0600` (claimed in [`bffi::core::handle`]), mirroring the task
//! table of `bffi-async`.

// Internal module aliases (the pre-merge crate names).
use crate::bffi_core;
use std::collections::VecDeque;
use std::sync::{Arc, Mutex, OnceLock};
use std::task::Waker;

use bffi_core::{Handle, Registry, TypeTag};

pub mod abi;

/// The type tag of the stream table.
const STREAM_TAG: TypeTag = TypeTag(0x0600);

/// The bounded buffer capacity of a push stream: a producer pushing
/// into a full buffer parks (its `push` future stays pending) until
/// the JS side drains room.
pub(crate) const PUSH_CAPACITY: usize = 256;

/// The wire form of one stream item: a complete `[tag][payload]`
/// record.
pub type EncodedItem = Vec<u8>;

/// A type that can cross a stream as one item record. Implemented
/// for the scalar matrix (numbers, `i64`, `u64`, `bool`, `String`,
/// `Vec<u8>`) and generated by `#[derive(BffiRecord)]` /
/// `#[derive(BffiEnum)]` for composites; `Result<T, E>` items encode
/// their `Err` as an error record (TAG 11).
pub trait BffiStreamItem {
    /// Appends the item as one complete wire record.
    fn encode_into(&self, out: &mut Vec<u8>);
}

macro_rules! stream_item_int {
    ($($ty:ty),* => $encoder:ident) => {
        $(
            impl BffiStreamItem for $ty {
                fn encode_into(&self, out: &mut Vec<u8>) {
                    crate::bffi_types::wire::$encoder(out, (*self).into());
                }
            }
        )*
    };
}

stream_item_int!(i8, i16, i32, u8, u16 => encode_i32);

impl BffiStreamItem for u32 {
    fn encode_into(&self, out: &mut Vec<u8>) {
        // The f64 record is exact over the whole u32 range.
        crate::bffi_types::wire::encode_f64(out, f64::from(*self));
    }
}

impl BffiStreamItem for f32 {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_f64(out, f64::from(*self));
    }
}

impl BffiStreamItem for f64 {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_f64(out, *self);
    }
}

impl BffiStreamItem for i64 {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_i64(out, *self);
    }
}

impl BffiStreamItem for u64 {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_u64(out, *self);
    }
}

impl BffiStreamItem for bool {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_bool(out, *self);
    }
}

impl BffiStreamItem for String {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_str(out, self);
    }
}

impl BffiStreamItem for Vec<u8> {
    fn encode_into(&self, out: &mut Vec<u8>) {
        crate::bffi_types::wire::encode_bytes(out, self);
    }
}

impl<T: BffiStreamItem, E: std::fmt::Display> BffiStreamItem for Result<T, E> {
    fn encode_into(&self, out: &mut Vec<u8>) {
        match self {
            Ok(value) => value.encode_into(out),
            Err(error) => crate::bffi_types::wire::encode_error(out, &error.to_string()),
        }
    }
}

/// The live state of one stream: a pull iterator or a push buffer,
/// terminal in `Done`/`Errored`.
pub(crate) struct StreamEntry {
    state: Mutex<StreamState>,
    /// The JS wake trampoline registered by the typed wrapper (the
    /// `bffi_stream_set_wake` ABI): fired through the event loop
    /// when the buffer transitions empty -> non-empty or the stream
    /// completes/fails, so a waiting pull resumes without polling.
    wake: Mutex<Option<usize>>,
    /// The JS thread that registered the wake (see
    /// `bffi::callback::thread`): the trampoline belongs to that
    /// isolate, so the wake job is delivered there. `0` = the
    /// process was unbound (pure-Rust usage) - legacy untargeted
    /// delivery.
    #[cfg(feature = "event-loop")]
    wake_thread: std::sync::atomic::AtomicU64,
}

enum StreamState {
    /// The iterator is alive: up to `max` items per pull.
    Items(Box<dyn Iterator<Item = Result<EncodedItem, String>> + Send>),
    /// The bounded push buffer (a producer future feeds it).
    Buffer(PushState),
    /// The iterator is exhausted (or the stream was dropped early).
    Done,
    /// A panic poisoned the iterator; the message reports it.
    Errored(String),
}

/// The bounded buffer of a push stream.
pub(crate) struct PushState {
    queue: VecDeque<EncodedItem>,
    completed: bool,
    error: Option<String>,
    /// Producers parked on a full buffer.
    producers: Vec<Waker>,
}

impl PushState {
    fn new() -> Self {
        Self {
            queue: VecDeque::new(),
            completed: false,
            error: None,
            producers: Vec::new(),
        }
    }

    /// Wakes every parked producer (room freed or the stream ended).
    fn wake_producers(&mut self) {
        for waker in self.producers.drain(..) {
            waker.wake();
        }
    }
}

/// Everything that can go wrong at the stream surface.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum StreamError {
    /// The stream table has no free slot.
    TableFull,
    /// Table initialization ever failed (sticky).
    TagInUse,
    /// The handle is null, stale or foreign.
    InvalidHandle,
    /// The iterator panicked on an earlier pull, or a `Result` item
    /// carried an `Err`: the message reports it. Sticky.
    Errored(String),
    /// The buffer is empty while the producer is still alive: retry
    /// after a tick (the JS wrapper drives the retry).
    Pending,
    /// The stream is done (exhausted, dropped or completed): a
    /// producer pushing onto it ends.
    Closed,
}

impl std::fmt::Display for StreamError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TableFull => write!(f, "the bffi-stream table is full"),
            Self::TagInUse => write!(f, "the bffi-stream tag is already declared"),
            Self::InvalidHandle => write!(f, "unknown or stale stream handle"),
            Self::Errored(message) => write!(f, "the stream failed: {message}"),
            Self::Pending => write!(f, "no items ready yet - the producer is still alive"),
            Self::Closed => write!(f, "the stream is closed"),
        }
    }
}

impl std::error::Error for StreamError {}

/// Unified-format conversion onto existing codes; the domain error
/// is preserved as the source.
impl From<StreamError> for bffi_core::BffiError {
    fn from(error: StreamError) -> Self {
        use bffi_core::ErrorCode;
        let code = match &error {
            StreamError::TableFull => ErrorCode::TableFull,
            StreamError::TagInUse => ErrorCode::InvalidTag,
            StreamError::InvalidHandle | StreamError::Closed => ErrorCode::InvalidHandle,
            StreamError::Errored(_) => ErrorCode::Error,
            StreamError::Pending => ErrorCode::Pending,
        };
        let message = error.to_string();
        bffi_core::BffiError::with_source(code, message, error)
    }
}

/// The result of one chunk pull: `Done` when the iterator is
/// exhausted, otherwise up to `max` pre-encoded item records.
#[derive(Debug, PartialEq, Eq)]
pub enum Chunk {
    /// The stream is exhausted.
    Done,
    /// Up to `max` items, each one complete wire record.
    Items(Vec<Vec<u8>>),
}

fn tables() -> Result<(), bffi_core::RegistryError> {
    static TABLES: OnceLock<Result<(), bffi_core::RegistryError>> = OnceLock::new();
    *TABLES.get_or_init(|| {
        Registry::global()
            .declare::<StreamEntry>(STREAM_TAG)
            .map_err(|_| bffi_core::RegistryError::TagAlreadyRegistered(STREAM_TAG))
    })
}

/// Registers the JS wake trampoline for a stream: the raw pointer of
/// a `(u64) -> void` bun:ffi `JSCallback` the typed wrapper created.
/// `false` for unknown/stale/foreign handles.
///
/// The CALLING thread is recorded as the wake's owner: the
/// trampoline belongs to that isolate, and [`fire_wake`] delivers the
/// wake job there (never across an isolate boundary).
#[cfg(feature = "event-loop")]
pub fn set_wake(handle: Handle, ptr: usize) -> bool {
    use std::sync::atomic::Ordering;
    match Registry::global().get_typed::<StreamEntry>(handle) {
        Some(entry) => {
            *entry
                .wake
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner) = Some(ptr);
            entry
                .wake_thread
                .store(crate::bffi_callback::binding_thread(), Ordering::Release);
            true
        }
        None => false,
    }
}

/// Without an event loop there is no wake delivery: the JS pull
/// relies on its polling timer (the documented contract).
#[cfg(not(feature = "event-loop"))]
pub fn set_wake(handle: Handle, ptr: usize) -> bool {
    match Registry::global().get_typed::<StreamEntry>(handle) {
        Some(entry) => {
            *entry
                .wake
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner) = Some(ptr);
            true
        }
        None => false,
    }
}

/// Fires the wake trampoline through the event loop: the queued job
/// runs on the JS thread and resolves the pull that is waiting on
/// the stream. Best-effort - a stopped loop (or an unregistered
/// trampoline) simply keeps the poll-retry contract working.
///
/// TARGETED delivery: when the wake has an owning isolate (its
/// `set_wake` ran on a registered JS thread), the job is queued on
/// that thread's slot queue; a departed worker leaves the wake
/// undeliverable and the JS pull falls back to its bounded timer.
#[cfg(feature = "event-loop")]
fn fire_wake(entry: &StreamEntry) {
    use std::sync::atomic::Ordering;
    let ptr = *entry
        .wake
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let Some(ptr) = ptr else {
        return;
    };
    let thread = entry.wake_thread.load(Ordering::Acquire);
    let job = Box::new(move || {
        // SAFETY: `ptr` is the bun:ffi JSCallback trampoline the JS
        // wrapper registered for this stream (`(u64) -> void`); the
        // wrapper never closes it while the stream can still fire
        // (the callback outlives the stream by contract), and the
        // call runs on the OWNING JS thread inside its loop drain.
        let wake: extern "C" fn(u64) = unsafe { std::mem::transmute(ptr) };
        wake(0);
    });
    let queued = if thread == 0 {
        crate::bffi_event_loop::enqueue(job)
    } else {
        crate::bffi_event_loop::enqueue_to(thread, job)
    };
    if queued.is_err() {
        // The loop was stopped, or the owning isolate is gone: the
        // wake is undeliverable and the JS pull falls back to its
        // bounded timer (documented).
    }
}

/// Without an event loop there is no wake delivery: the JS pull
/// relies on its polling timer (the documented contract).
#[cfg(not(feature = "event-loop"))]
fn fire_wake(_entry: &StreamEntry) {}

/// Registers a stream over `iter` and returns its handle. Items are
/// the pre-encoded records; an `Err` item terminates the stream with
/// that message (the `Result`-item adapter of the macros).
///
/// # Errors
///
/// [`StreamError::TableFull`] when the stream table has no free
/// slot, or [`StreamError::TagInUse`] if table initialization ever
/// failed.
pub fn spawn(
    iter: Box<dyn Iterator<Item = Result<EncodedItem, String>> + Send>,
) -> Result<Handle, StreamError> {
    tables().map_err(|_| StreamError::TagInUse)?;
    Registry::global()
        .insert(
            STREAM_TAG,
            Arc::new(StreamEntry {
                state: Mutex::new(StreamState::Items(iter)),
                wake: Mutex::new(None),
                #[cfg(feature = "event-loop")]
                wake_thread: std::sync::atomic::AtomicU64::new(0),
            }),
        )
        .map_err(|_| StreamError::TableFull)
}

/// Registers an empty push buffer and returns its handle plus the
/// producer context. The producer future feeds
/// [`Ctx::push`](Ctx::push) and ends with [`Ctx::complete`] /
/// [`Ctx::fail`].
///
/// # Errors
///
/// The same as [`spawn`].
pub fn spawn_push<T: BffiStreamItem>() -> Result<(Handle, Ctx<T>), StreamError> {
    tables().map_err(|_| StreamError::TagInUse)?;
    let handle = Registry::global()
        .insert(
            STREAM_TAG,
            Arc::new(StreamEntry {
                state: Mutex::new(StreamState::Buffer(PushState::new())),
                wake: Mutex::new(None),
                #[cfg(feature = "event-loop")]
                wake_thread: std::sync::atomic::AtomicU64::new(0),
            }),
        )
        .map_err(|_| StreamError::TableFull)?;
    Ok((
        handle,
        Ctx {
            handle,
            _item: std::marker::PhantomData,
        },
    ))
}

/// Pulls up to `max` pre-encoded item records. An empty `max` yields
/// an empty chunk (the JS side always sends a positive budget).
///
/// # Errors
///
/// [`StreamError::InvalidHandle`] for null/stale/foreign handles,
/// [`StreamError::Errored`] when the iterator panicked on an earlier
/// pull (or this one - the panic is caught here, the stream is
/// marked errored and stays dead).
pub fn next_chunk(handle: Handle, max: usize) -> Result<Chunk, StreamError> {
    let entry = Registry::global()
        .get_typed::<StreamEntry>(handle)
        .ok_or(StreamError::InvalidHandle)?;
    let mut state = entry
        .state
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    match &mut *state {
        StreamState::Done => Ok(Chunk::Done),
        StreamState::Errored(message) => Err(StreamError::Errored(message.clone())),
        StreamState::Items(iter) => {
            let mut items = Vec::new();
            for _ in 0..max {
                // Catch the panic so the entry mutex never stays
                // poisoned and the stream reports a clean, sticky
                // error instead of taking down the host.
                let next = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| iter.next()));
                match next {
                    Ok(Some(Ok(record))) => items.push(record),
                    Ok(Some(Err(message))) => {
                        // A `Result` item's `Err`: the stream
                        // terminates with that message.
                        *state = StreamState::Errored(message.clone());
                        return Err(StreamError::Errored(message));
                    }
                    Ok(None) => {
                        *state = StreamState::Done;
                        break;
                    }
                    Err(payload) => {
                        let message = bffi_core::panic_message(payload.as_ref());
                        *state = StreamState::Errored(message.clone());
                        return Err(StreamError::Errored(message));
                    }
                }
            }
            Ok(Chunk::Items(items))
        }
        StreamState::Buffer(push) => {
            let mut items = Vec::new();
            while items.len() < max {
                let Some(record) = push.queue.pop_front() else {
                    break;
                };
                items.push(record);
            }
            // Room freed: parked producers fill the buffer again.
            push.wake_producers();
            if !items.is_empty() {
                return Ok(Chunk::Items(items));
            }
            if let Some(message) = &push.error {
                return Err(StreamError::Errored(message.clone()));
            }
            if push.completed {
                *state = StreamState::Done;
                return Ok(Chunk::Done);
            }
            Err(StreamError::Pending)
        }
    }
}

/// Releases the stream behind `handle` (an early exit before the
/// iterator is exhausted); `true` when a live stream was dropped.
/// The GC finalizer and an explicit JS `return()` both route here;
/// dropping twice or after exhaustion reports `false` and stays
/// silent. A producer pushing onto a dropped stream sees
/// [`StreamError::Closed`] and ends.
#[must_use]
pub fn drop_stream(handle: Handle) -> bool {
    match Registry::global().get_typed::<StreamEntry>(handle) {
        Some(entry) => {
            let mut state = entry
                .state
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner);
            match &mut *state {
                StreamState::Buffer(push) => {
                    push.wake_producers();
                    *state = StreamState::Done;
                    true
                }
                StreamState::Items(_) => {
                    *state = StreamState::Done;
                    true
                }
                _ => false,
            }
        }
        None => false,
    }
}

/// Whether the handle names a live (not yet exhausted or errored)
/// stream.
#[must_use]
pub fn is_live(handle: Handle) -> bool {
    match Registry::global().get_typed::<StreamEntry>(handle) {
        Some(entry) => {
            let state = entry
                .state
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner);
            match &*state {
                StreamState::Items(_) => true,
                StreamState::Buffer(push) => !push.completed && push.error.is_none(),
                _ => false,
            }
        }
        None => false,
    }
}

/// The producer-side context of a push stream: [`Ctx::push`]
/// appends one item (parking with backpressure while the buffer is
/// full), [`Ctx::complete`] ends the stream successfully,
/// [`Ctx::fail`] terminates it with an error. Dropping the stream
/// (JS early exit) fails the pending pushes - the producer ends.
pub struct Ctx<T> {
    handle: Handle,
    _item: std::marker::PhantomData<fn() -> T>,
}

impl<T> Clone for Ctx<T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> Copy for Ctx<T> {}

impl<T: BffiStreamItem> Ctx<T> {
    /// Appends one item; resolves once the item is in the buffer.
    /// Backpressures (stays pending) while the buffer is full, and
    /// resolves with [`StreamError::Closed`] once the stream is done.
    pub fn push(&self, item: T) -> Push<'_, T> {
        Push {
            handle: self.handle,
            item: Some(item),
            _life: std::marker::PhantomData,
        }
    }

    /// Ends the stream successfully; items already in the buffer
    /// stay deliverable.
    pub fn complete(&self) -> Result<(), StreamError> {
        Self::complete_handle(self.handle)
    }

    /// Terminates the stream with an error; items already in the
    /// buffer stay deliverable, then the JS side sees the error.
    pub fn fail(&self, message: &str) -> Result<(), StreamError> {
        Self::fail_handle(self.handle, message.to_owned())
    }

    /// The raw stream handle (probes, tests).
    #[must_use]
    pub fn as_raw(&self) -> u64 {
        self.handle.as_u64()
    }

    pub(crate) fn complete_handle(handle: Handle) -> Result<(), StreamError> {
        let entry = Registry::global()
            .get_typed::<StreamEntry>(handle)
            .ok_or(StreamError::InvalidHandle)?;
        let mut state = entry
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        match &mut *state {
            StreamState::Buffer(push) => {
                push.completed = true;
                push.wake_producers();
                // A pull waiting on Pending learns the end instantly.
                fire_wake(&entry);
                Ok(())
            }
            StreamState::Done | StreamState::Items(_) => Err(StreamError::Closed),
            StreamState::Errored(message) => Err(StreamError::Errored(message.clone())),
        }
    }

    pub(crate) fn fail_handle(handle: Handle, message: String) -> Result<(), StreamError> {
        let entry = Registry::global()
            .get_typed::<StreamEntry>(handle)
            .ok_or(StreamError::InvalidHandle)?;
        let mut state = entry
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        match &mut *state {
            StreamState::Buffer(push) => {
                push.error = Some(message);
                push.wake_producers();
                // A pull waiting on Pending learns the error instantly.
                fire_wake(&entry);
                Ok(())
            }
            StreamState::Done | StreamState::Items(_) => Err(StreamError::Closed),
            StreamState::Errored(existing) => Err(StreamError::Errored(existing.clone())),
        }
    }
}

/// The future of one [`Ctx::push`]: resolves when the item is in
/// the buffer.
pub struct Push<'a, T> {
    handle: Handle,
    item: Option<T>,
    _life: std::marker::PhantomData<&'a ()>,
}

// Safe: the future never projects pinned fields - `item` is taken
// by value on resolution and the handle is `Copy`.
impl<T> Unpin for Push<'_, T> {}

impl<T: BffiStreamItem> std::future::Future for Push<'_, T> {
    type Output = Result<(), StreamError>;

    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        let entry = match Registry::global().get_typed::<StreamEntry>(self.handle) {
            Some(entry) => entry,
            None => {
                return std::task::Poll::Ready(Err(StreamError::Closed));
            }
        };
        let mut state = entry
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        match &mut *state {
            StreamState::Buffer(push) => {
                if let Some(message) = &push.error {
                    return std::task::Poll::Ready(Err(StreamError::Errored(message.clone())));
                }
                if push.completed {
                    return std::task::Poll::Ready(Err(StreamError::Closed));
                }
                if push.queue.len() < PUSH_CAPACITY {
                    let Some(item) = self.item.take() else {
                        // Polled after resolution: treat as closed
                        // (cannot happen with a well-formed future).
                        return std::task::Poll::Ready(Err(StreamError::Closed));
                    };
                    let mut record = Vec::new();
                    item.encode_into(&mut record);
                    let was_empty = push.queue.is_empty();
                    push.queue.push_back(record);
                    if was_empty {
                        // Empty -> non-empty: a pull may be waiting
                        // on Pending; wake it through the loop.
                        fire_wake(&entry);
                    }
                    std::task::Poll::Ready(Ok(()))
                } else {
                    // Full: park until the next pull frees room.
                    let waker = cx.waker().clone();
                    if !push.producers.iter().any(|w| w.will_wake(&waker)) {
                        push.producers.push(waker);
                    }
                    std::task::Poll::Pending
                }
            }
            StreamState::Done | StreamState::Items(_) => {
                std::task::Poll::Ready(Err(StreamError::Closed))
            }
            StreamState::Errored(message) => {
                std::task::Poll::Ready(Err(StreamError::Errored(message.clone())))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{Chunk, StreamError, drop_stream, is_live, next_chunk, spawn};
    type ItemResult = Result<Vec<u8>, String>;

    fn numbers(range: std::ops::Range<u32>) -> Box<dyn Iterator<Item = ItemResult> + Send> {
        use crate::bffi_types::wire as w;
        Box::new(range.map(move |n| {
            let mut out = Vec::new();
            w::encode_i32(&mut out, n as i32);
            Ok(out)
        }))
    }

    #[test]
    fn chunks_yield_in_order_until_done() {
        let handle = spawn(numbers(0..5)).expect("spawned");
        assert!(is_live(handle));

        let mut seen = Vec::new();
        while let Chunk::Items(items) = next_chunk(handle, 2).expect("chunk") {
            seen.extend(items);
        }
        assert_eq!(seen.len(), 5);
        assert!(!is_live(handle), "exhausted streams are not live");
    }

    #[test]
    fn max_limits_the_chunk_and_the_pull_resumes() {
        let handle = spawn(numbers(0..4)).expect("spawned");
        match next_chunk(handle, 3).expect("first chunk") {
            Chunk::Items(items) => assert_eq!(items.len(), 3),
            Chunk::Done => panic!("stream is not exhausted"),
        }
        match next_chunk(handle, 3).expect("second chunk") {
            Chunk::Items(items) => assert_eq!(items.len(), 1),
            Chunk::Done => panic!("one item remains"),
        }
        assert_eq!(next_chunk(handle, 3).expect("done"), Chunk::Done);
    }

    #[test]
    fn empty_max_yields_an_empty_chunk() {
        let handle = spawn(numbers(0..1)).expect("spawned");
        assert_eq!(
            next_chunk(handle, 0).expect("empty budget"),
            Chunk::Items(Vec::new())
        );
    }

    #[test]
    fn invalid_and_dropped_handles_report_cleanly() {
        assert!(matches!(
            next_chunk(crate::bffi_core::Handle::NULL, 4),
            Err(StreamError::InvalidHandle)
        ));
        let handle = spawn(numbers(0..2)).expect("spawned");
        assert!(drop_stream(handle), "first drop wins");
        assert!(!drop_stream(handle), "second drop stays silent");
        assert_eq!(next_chunk(handle, 4).expect("done"), Chunk::Done);
    }

    #[test]
    fn a_panicking_iterator_poisons_only_its_own_stream() {
        struct Boom(usize);
        impl Iterator for Boom {
            type Item = ItemResult;
            fn next(&mut self) -> Option<ItemResult> {
                if self.0 == 0 {
                    panic!("stream boom");
                }
                self.0 -= 1;
                Some(Ok(Vec::new()))
            }
        }
        let healthy = spawn(numbers(0..1)).expect("spawned");
        let poisoned = spawn(Box::new(Boom(0))).expect("spawned");

        let error = next_chunk(poisoned, 4).expect_err("poisoned");
        assert!(
            matches!(error, StreamError::Errored(ref message) if message.contains("stream boom")),
            "the panic message surfaces: {error:?}"
        );
        // Sticky: the stream stays dead.
        assert!(matches!(
            next_chunk(poisoned, 4),
            Err(StreamError::Errored(_))
        ));
        // The table (and other streams) survive.
        assert_eq!(
            next_chunk(healthy, 4).expect("healthy chunk"),
            Chunk::Items(vec![vec![crate::bffi_types::wire::TAG_I32, 0, 0, 0, 0,]])
        );
    }

    #[test]
    fn push_buffer_delivers_in_order_and_completes() {
        use super::spawn_push;
        let (handle, ctx) = spawn_push::<i32>().expect("spawned");
        push_now(&ctx, 1);
        push_now(&ctx, 2);
        ctx.complete().expect("completed");

        let mut seen = Vec::new();
        while let Chunk::Items(items) = next_chunk(handle, 4).expect("chunk") {
            seen.extend(items);
        }
        assert_eq!(seen.len(), 2);
        assert!(!is_live(handle), "completed streams are not live");
    }

    #[test]
    fn push_backpressures_until_drained() {
        use super::{PUSH_CAPACITY, spawn_push};
        let (handle, ctx) = spawn_push::<i32>().expect("spawned");
        // Fill the buffer exactly.
        for i in 0..PUSH_CAPACITY as i32 {
            push_now(&ctx, i);
        }
        // The next push parks: the buffer is full and nothing drains.
        let mut fut = ctx.push(999);
        assert!(
            futures_poll(&mut fut).is_none(),
            "a parked push must stay pending while the buffer is full"
        );
        // Draining frees room and wakes the producer.
        match next_chunk(handle, PUSH_CAPACITY).expect("chunk") {
            Chunk::Items(items) => assert_eq!(items.len(), PUSH_CAPACITY),
            Chunk::Done => panic!("items were pushed"),
        }
        assert!(
            futures_poll(&mut fut).is_some(),
            "the waker fired: the push resolved"
        );
        let mut seen = Vec::new();
        while let Chunk::Items(items) = next_chunk(handle, PUSH_CAPACITY).expect("chunk") {
            seen.extend(items);
            if seen.len() == 1 {
                break;
            }
        }
        assert_eq!(seen.len(), 1, "exactly the parked item remains");
        // The producer never completed: the empty live buffer stays
        // Pending (the poll contract, not an error).
        assert!(matches!(
            next_chunk(handle, PUSH_CAPACITY),
            Err(StreamError::Pending)
        ));
    }

    #[test]
    fn drop_fails_pending_producers() {
        use super::spawn_push;
        let (handle, ctx) = spawn_push::<i32>().expect("spawned");
        assert!(drop_stream(handle), "first drop wins");
        let outcome = futures_poll(&mut ctx.push(1));
        assert!(
            matches!(outcome, Some(Err(StreamError::Closed))),
            "a push after the drop resolves with Closed"
        );
        assert!(ctx.complete().is_err(), "complete on a closed stream");
    }

    #[test]
    fn fail_terminates_with_the_message() {
        use super::spawn_push;
        let (handle, ctx) = spawn_push::<i32>().expect("spawned");
        ctx.fail("producer broke").expect("failed");
        assert!(
            matches!(
                next_chunk(handle, 4),
                Err(StreamError::Errored(ref message)) if message.contains("producer broke")
            ),
            "the error message surfaces"
        );
    }

    /// Pushes and asserts the item landed immediately (room was
    /// available).
    fn push_now<T: super::BffiStreamItem>(ctx: &super::Ctx<T>, item: T) {
        assert!(
            futures_poll(&mut ctx.push(item)).is_some(),
            "a push below capacity must resolve immediately"
        );
    }

    /// Polls a future once (no executor): `Some(output)` when ready.
    fn futures_poll<F>(fut: &mut F) -> Option<F::Output>
    where
        F: std::future::Future + Unpin,
    {
        use std::task::Poll;
        let waker = std::task::Waker::noop();
        let mut cx = std::task::Context::from_waker(waker);
        match std::pin::Pin::new(fut).poll(&mut cx) {
            Poll::Ready(output) => Some(output),
            Poll::Pending => None,
        }
    }
}
