// @generated by bffi codegen - do not edit.
// Source module: callbacks
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  makeTakeError,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "callbacks",
  "abiVersion": 1,
  "exportsHash": "4859311640586416465",
  "functions": [
    {
      "name": "callback_register",
      "export": "bffi_callback_register",
      "docs": [
        "Registers the native doubling callback `i32(i32)`; JS invokes it",
        "by handle through `invokeCallback` (the generic ABI)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "callback_invoke_status",
      "export": "bffi_callback_invoke_status",
      "docs": [
        "Invokes the native callback behind `handle` with one `i32` and",
        "returns the raw `ErrorCode` numeric value with the last error",
        "stored, so tests can pin exact codes (`0` = Ok, `12` =",
        "WrongThread, `4` = InvalidHandle). The typed invoke path is the",
        "generic ABI itself (`invokeCallback` on the JS side)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "a",
          "ts": "number",
          "abi": "i32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "callback_ptr",
      "export": "bffi_callback_ptr",
      "docs": [
        "Reads back the JS-side callback behind `handle` (the Rust -> JS",
        "direction): the opaque pointer token stored at bind time. The",
        "token is NEVER dereferenced by Rust - a LIVE call into JS through",
        "this pointer is the async delivery path's job (see the async",
        "example); here the e2e verifies storage, identity and revocation."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "bind_js_thread",
      "export": "bffi_bind_js_thread",
      "docs": [
        "Registers the CURRENT thread as a JS thread of this process",
        "(multi-isolate: every JS isolate registers its own thread;",
        "idempotent). Returns the raw `ErrorCode` numeric value: `0` =",
        "registered. The worker of the e2e test calls this before entering",
        "the loop drain."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "marshal_invoke",
      "export": "bffi_marshal_invoke",
      "docs": [
        "Marshals a job onto the RUNNING loop: the job invokes the callback",
        "behind `handle` with `a` ON THE RUNNER THREAD (where the JS thread",
        "gate passes) and stores the result into the process-wide slot (see",
        "[`last_invoked`]). Returns the raw `ErrorCode` numeric value: `0` =",
        "accepted, `12` = `WrongThread` (no runner is up)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "a",
          "ts": "number",
          "abi": "i32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "last_invoked",
      "export": "bffi_last_invoked",
      "docs": [
        "The value stored by the last executed marshal job (`0` before the",
        "first)."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "i32"
      },
      "out": "i32"
    },
    {
      "name": "loop_run",
      "export": "bffi_loop_run",
      "docs": [
        "Blocks the calling thread draining the loop until [`loop_stop`];",
        "returns the number of jobs executed by THIS runner. Intended for",
        "the worker thread of the e2e test (after `bind_js_thread`, so the",
        "marshalled callback invocations pass the JS-thread gate)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_stop",
      "export": "bffi_loop_stop",
      "docs": [
        "Stops the loop for good (sticky): `loop_run` returns."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_callback_register = new BigUint64Array(1);
  const sym_callback_register = sym("bffi_callback_register");
  const fn_callback_register = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("callback_register: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_callback_register(out_callback_register));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_callback_register failed: " + String(status));
    }
    return (out_callback_register[0] ?? 0n);
  };
  const out_callback_invoke_status = new Uint32Array(1);
  const sym_callback_invoke_status = sym("bffi_callback_invoke_status");
  const fn_callback_invoke_status = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("callback_invoke_status: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_callback_invoke_status(a0, a1, out_callback_invoke_status));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_callback_invoke_status failed: " + String(status));
    }
    return (out_callback_invoke_status[0] ?? 0);
  };
  const out_callback_ptr = new BigUint64Array(1);
  const sym_callback_ptr = sym("bffi_callback_ptr");
  const fn_callback_ptr = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("callback_ptr: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_callback_ptr(a0, out_callback_ptr));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_callback_ptr failed: " + String(status));
    }
    return (out_callback_ptr[0] ?? 0n);
  };
  const out_bind_js_thread = new Uint32Array(1);
  const sym_bind_js_thread = sym("bffi_bind_js_thread");
  const fn_bind_js_thread = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("bind_js_thread: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_bind_js_thread(out_bind_js_thread));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_bind_js_thread failed: " + String(status));
    }
    return (out_bind_js_thread[0] ?? 0);
  };
  const out_marshal_invoke = new Uint32Array(1);
  const sym_marshal_invoke = sym("bffi_marshal_invoke");
  const fn_marshal_invoke = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("marshal_invoke: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_marshal_invoke(a0, a1, out_marshal_invoke));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_marshal_invoke failed: " + String(status));
    }
    return (out_marshal_invoke[0] ?? 0);
  };
  const out_last_invoked = new Int32Array(1);
  const sym_last_invoked = sym("bffi_last_invoked");
  const fn_last_invoked = function (): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("last_invoked: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_last_invoked(out_last_invoked));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_last_invoked failed: " + String(status));
    }
    return (out_last_invoked[0] ?? 0);
  };
  const out_loop_run = new BigUint64Array(1);
  const sym_loop_run = sym("bffi_loop_run");
  const fn_loop_run = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_run: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_run(out_loop_run));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_run failed: " + String(status));
    }
    return (out_loop_run[0] ?? 0n);
  };
  const sym_loop_stop = sym("bffi_loop_stop");
  const fn_loop_stop = function (): void {
    if (arguments.length !== 0) {
      throw new Error("loop_stop: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_stop());
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_stop failed: " + String(status));
    }
  };
  return {
    "callback_register": fn_callback_register,
    "callback_invoke_status": fn_callback_invoke_status,
    "callback_ptr": fn_callback_ptr,
    "bind_js_thread": fn_bind_js_thread,
    "marshal_invoke": fn_marshal_invoke,
    "last_invoked": fn_last_invoked,
    "loop_run": fn_loop_run,
    "loop_stop": fn_loop_stop,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
