// @generated by bffi codegen - do not edit.
// Source module: wry
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen, ptr } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  encodeValue,
  jsToWire,
  makeTakeError,
  tablesOf,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "wry",
  "abiVersion": 1,
  "exportsHash": "3167894252113368214",
  "functions": [
    {
      "name": "webview_open",
      "export": "bffi_webview_open",
      "docs": [
        "Opens a webview window described by `config` (inline `html` or a",
        "`url`, optional `title`/`width`/`height`/`devtools`) and returns",
        "its opaque handle. The first call spawns the dedicated loop",
        "thread (winit event loop + window + wry surface live there);",
        "the Bun thread only waits, bounded, for the creation reply."
      ],
      "params": [
        {
          "name": "config",
          "ts": "WebviewConfig",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "webview_eval",
      "export": "bffi_webview_eval",
      "docs": [
        "Evaluates `js` in the webview behind `handle` (proxied onto the",
        "loop thread; fire-and-forget - the script's result stays in the",
        "page)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "js",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_close",
      "export": "bffi_webview_close",
      "docs": [
        "Closes the webview behind `handle` (also the title-bar X path):",
        "the loop thread drops the window and exits when it was the last",
        "one - then [`webview_poll_exit`] flips to `true`."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_bind_ipc",
      "export": "bffi_webview_bind_ipc",
      "docs": [
        "Wires the IPC roundtrip of the webview behind `handle` to a JS",
        "handler: `ipc` is a JS-BOUND callback handle - the JS side wraps",
        "its handler into a `bun:ffi` `JSCallback` declared as",
        "`{ args: [\"cstring\"], returns: \"void\" }` and binds it through",
        "`bffi_callback_bind` with the signature `unit(str)` (wire tags",
        "`[0, 5]`), exactly the `examples/callbacks` bind pattern. The",
        "request body arrives as the `cstring` argument; the handler",
        "answers through [`webview_ipc_reply`]. Native side invokes the",
        "handle with `invoke_wait(..., [Value::Str(body)])` from the loop",
        "thread - the dispatch calls the bound pointer on the JS thread."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "ipc",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_ipc_reply",
      "export": "bffi_webview_ipc_reply",
      "docs": [
        "The IPC message box, JS side: stores the reply JSON (embedded",
        "into the resolve script verbatim, so it MUST be valid JSON).",
        "Called by the bound callback before it returns."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "reply",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_poll_exit",
      "export": "bffi_webview_poll_exit",
      "docs": [
        "Whether the loop thread has finished (the last webview closed)."
      ],
      "params": [],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "The non-blocking drain the JS side calls while native threads",
        "wait (`pumpUntil` from `@z2net/bffi`): the marshalled callback",
        "invocation executes here, on the bound JS thread."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "WebviewConfig",
      "docs": [
        "The open request: everything optional (`None` rides the",
        "`TAG_UNIT` wire byte and arrives as `null` on the JS side).",
        "Exactly one of `url`/`html` should be set; `html` wins if both",
        "are (wry ignores `url` when `html` is present)."
      ],
      "fields": [
        {
          "name": "url",
          "docs": [
            "The URL to load."
          ],
          "ts": "string | null"
        },
        {
          "name": "html",
          "docs": [
            "The inline HTML to load (overrides `url`)."
          ],
          "ts": "string | null"
        },
        {
          "name": "title",
          "docs": [
            "The window title."
          ],
          "ts": "string | null"
        },
        {
          "name": "width",
          "docs": [
            "The window width (`1024` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "height",
          "docs": [
            "The window height (`768` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "devtools",
          "docs": [
            "Whether devtools are enabled."
          ],
          "ts": "boolean | null"
        }
      ]
    }
  ],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const tables = tablesOf(moduleJson);
  const wireBytes = (ts: string, value: unknown, ctx: string): Uint8Array => {
    const record = jsToWire(tables, ts, value, ctx);
    const bytes: number[] = [];
    encodeValue(bytes, record);
    return new Uint8Array(bytes);
  };
  const out_webview_open = new BigUint64Array(1);
  const sym_webview_open = sym("bffi_webview_open");
  const fn_webview_open = function (a0: TsOf<"WebviewConfig", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("webview_open: expected 1 argument(s), got " + arguments.length);
    }
    const wire_webview_open_config = wireBytes("WebviewConfig", a0, "webview_open(config)");
    const status = Number(sym_webview_open(wire_webview_open_config.length > 0 ? ptr(wire_webview_open_config) : null, wire_webview_open_config.length, out_webview_open));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_open failed: " + String(status));
    }
    return (out_webview_open[0] ?? 0n);
  };
  const sym_webview_eval = sym("bffi_webview_eval");
  const fn_webview_eval = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("webview_eval: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_webview_eval(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_eval failed: " + String(status));
    }
  };
  const sym_webview_close = sym("bffi_webview_close");
  const fn_webview_close = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("webview_close: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_webview_close(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_close failed: " + String(status));
    }
  };
  const sym_webview_bind_ipc = sym("bffi_webview_bind_ipc");
  const fn_webview_bind_ipc = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("webview_bind_ipc: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_webview_bind_ipc(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_bind_ipc failed: " + String(status));
    }
  };
  const sym_webview_ipc_reply = sym("bffi_webview_ipc_reply");
  const fn_webview_ipc_reply = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("webview_ipc_reply: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_webview_ipc_reply(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_ipc_reply failed: " + String(status));
    }
  };
  const out_webview_poll_exit = new Uint8Array(1);
  const sym_webview_poll_exit = sym("bffi_webview_poll_exit");
  const fn_webview_poll_exit = function (): TsOf<"boolean", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("webview_poll_exit: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_webview_poll_exit(out_webview_poll_exit));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_webview_poll_exit failed: " + String(status));
    }
    return (out_webview_poll_exit[0] ?? 0) !== 0;
  };
  const out_loop_pump = new BigUint64Array(1);
  const sym_loop_pump = sym("bffi_loop_pump");
  const fn_loop_pump = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pump: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pump(out_loop_pump));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pump failed: " + String(status));
    }
    return (out_loop_pump[0] ?? 0n);
  };
  return {
    "webview_open": fn_webview_open,
    "webview_eval": fn_webview_eval,
    "webview_close": fn_webview_close,
    "webview_bind_ipc": fn_webview_bind_ipc,
    "webview_ipc_reply": fn_webview_ipc_reply,
    "webview_poll_exit": fn_webview_poll_exit,
    "loop_pump": fn_loop_pump,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
