// @generated by bffi codegen - do not edit.
// Source module: wry

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "wry",
  "functions": [
    {
      "name": "webview_open",
      "export": "bffi_webview_open",
      "docs": [
        "Opens a webview window described by `config` (inline `html` or a",
        "`url`, optional `title`/`width`/`height`/`devtools`) and returns",
        "its opaque handle. The first call spawns the dedicated loop",
        "thread (winit event loop + window + wry surface live there);",
        "the Bun thread only waits, bounded, for the creation reply."
      ],
      "params": [
        {
          "name": "config",
          "ts": "WebviewConfig",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "webview_eval",
      "export": "bffi_webview_eval",
      "docs": [
        "Evaluates `js` in the webview behind `handle` (proxied onto the",
        "loop thread; fire-and-forget - the script's result stays in the",
        "page)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "js",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_close",
      "export": "bffi_webview_close",
      "docs": [
        "Closes the webview behind `handle` (also the title-bar X path):",
        "the loop thread drops the window and exits when it was the last",
        "one - then [`webview_poll_exit`] flips to `true`."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_bind_ipc",
      "export": "bffi_webview_bind_ipc",
      "docs": [
        "Wires the IPC roundtrip of the webview behind `handle` to a JS",
        "handler: `js_ptr` is the raw `bun:ffi` `JSCallback` pointer of a",
        "callback declared as `{ args: [\"cstring\"], returns: \"void\" }`",
        "(the request body arrives as the argument; the handler answers",
        "through [`webview_ipc_reply`] - the same raw-pointer convention",
        "as `bffi_async_attach`). Native side registers a forwarder",
        "callback whose body `invoke_wait` marshals onto the JS thread,",
        "where the pointer call is synchronous."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "js_ptr",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_ipc_reply",
      "export": "bffi_webview_ipc_reply",
      "docs": [
        "The IPC message box, JS side: stores the reply JSON (embedded",
        "into the resolve script verbatim, so it MUST be valid JSON).",
        "Called by the bound callback before it returns."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "reply",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "webview_poll_exit",
      "export": "bffi_webview_poll_exit",
      "docs": [
        "Whether the loop thread has finished (the last webview closed)."
      ],
      "params": [],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "The non-blocking drain the JS side calls while native threads",
        "wait (`pumpUntil` from `@z2net/bffi`): the marshalled callback",
        "invocation executes here, on the bound JS thread."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "WebviewConfig",
      "docs": [
        "The open request: everything optional (`None` rides the",
        "`TAG_UNIT` wire byte and arrives as `null` on the JS side).",
        "Exactly one of `url`/`html` should be set; `html` wins if both",
        "are (wry ignores `url` when `html` is present)."
      ],
      "fields": [
        {
          "name": "url",
          "docs": [
            "The URL to load."
          ],
          "ts": "string | null"
        },
        {
          "name": "html",
          "docs": [
            "The inline HTML to load (overrides `url`)."
          ],
          "ts": "string | null"
        },
        {
          "name": "title",
          "docs": [
            "The window title."
          ],
          "ts": "string | null"
        },
        {
          "name": "width",
          "docs": [
            "The window width (`1024` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "height",
          "docs": [
            "The window height (`768` when `None`)."
          ],
          "ts": "number | null"
        },
        {
          "name": "devtools",
          "docs": [
            "Whether devtools are enabled."
          ],
          "ts": "boolean | null"
        }
      ]
    }
  ],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
