// @generated by bffi codegen - do not edit.
// Source module: records
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen, ptr } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeAt,
  encodeValue,
  jsToWire,
  makeReadBuffer,
  makeTakeError,
  tablesOf,
  wireToJs,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "records",
  "abiVersion": 1,
  "exportsHash": "9616268554654068833",
  "functions": [
    {
      "name": "make_sample",
      "export": "bffi_make_sample",
      "docs": [
        "Builds a sample from primitives."
      ],
      "params": [
        {
          "name": "at",
          "ts": "number",
          "abi": "f64"
        },
        {
          "name": "weight",
          "ts": "number",
          "abi": "i32"
        },
        {
          "name": "label",
          "ts": "string",
          "abi": "cstring"
        },
        {
          "name": "axis",
          "ts": "Axis",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Sample",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "recenter",
      "export": "bffi_recenter",
      "docs": [
        "Shifts a sample along its axis (record in, record out)."
      ],
      "params": [
        {
          "name": "sample",
          "ts": "Sample",
          "abi": "ptr_len"
        },
        {
          "name": "dx",
          "ts": "number",
          "abi": "f64"
        }
      ],
      "ret": {
        "ts": "Sample",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "total_weight",
      "export": "bffi_total_weight",
      "docs": [
        "Sums the weights of a sample sequence."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "i64"
      },
      "out": "i64"
    },
    {
      "name": "distances",
      "export": "bffi_distances",
      "docs": [
        "The absolute positions of a sample sequence."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "number[]",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "labels",
      "export": "bffi_labels",
      "docs": [
        "The station labels of a sample sequence."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "string[]",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "label_bytes",
      "export": "bffi_label_bytes",
      "docs": [
        "The UTF-8 bytes of each label: the nested byte-vector sequence",
        "(`Vec<Vec<u8>>`) round trip."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Uint8Array[]",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "heaviest",
      "export": "bffi_heaviest",
      "docs": [
        "The heaviest sample, or `None` on an empty sequence (`Option`",
        "of a named composite: `Sample | null` on the JS side)."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Sample | null",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "classify",
      "export": "bffi_classify",
      "docs": [
        "The axis of the first sample; an empty sequence is a domain",
        "error."
      ],
      "params": [
        {
          "name": "samples",
          "ts": "Sample[]",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Axis",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "echo_profile",
      "export": "bffi_echo_profile",
      "docs": [
        "Echoes a profile back: `Option` fields round trip, `None`",
        "arriving as `null` on the JS side."
      ],
      "params": [
        {
          "name": "profile",
          "ts": "Profile",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Profile",
        "abi": "buffer"
      },
      "out": "handle"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "Sample",
      "docs": [
        "One measurement sample."
      ],
      "fields": [
        {
          "name": "at",
          "docs": [
            "Where it was taken."
          ],
          "ts": "number"
        },
        {
          "name": "weight",
          "docs": [
            "How heavy the reading was."
          ],
          "ts": "number"
        },
        {
          "name": "label",
          "docs": [
            "The station label."
          ],
          "ts": "string"
        },
        {
          "name": "axis",
          "docs": [
            "The axis it was taken along."
          ],
          "ts": "Axis"
        }
      ]
    },
    {
      "name": "Profile",
      "docs": [
        "A station profile over the optional-field flavors: `None` fields",
        "ride the `TAG_UNIT` wire byte and arrive as `null` in JS."
      ],
      "fields": [
        {
          "name": "nick",
          "docs": [
            "The optional station name."
          ],
          "ts": "string | null"
        },
        {
          "name": "level",
          "docs": [
            "The optional operator level."
          ],
          "ts": "number | null"
        },
        {
          "name": "rank",
          "docs": [
            "The optional station id (exact `u64`)."
          ],
          "ts": "bigint | null"
        },
        {
          "name": "muted",
          "docs": [
            "The optional maintenance flag."
          ],
          "ts": "boolean | null"
        },
        {
          "name": "avatar",
          "docs": [
            "The optional logo bytes."
          ],
          "ts": "Uint8Array | null"
        },
        {
          "name": "home",
          "docs": [
            "The optional home sample."
          ],
          "ts": "Sample | null"
        }
      ]
    }
  ],
  "enums": [
    {
      "name": "Axis",
      "docs": [
        "The measurement axis."
      ],
      "variants": [
        {
          "name": "Horizontal",
          "docs": [
            "Along the X axis."
          ]
        },
        {
          "name": "Vertical",
          "docs": [
            "Along the Y axis."
          ]
        }
      ]
    }
  ],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const tables = tablesOf(moduleJson);
  const wireBytes = (ts: string, value: unknown, ctx: string): Uint8Array => {
    const record = jsToWire(tables, ts, value, ctx);
    const bytes: number[] = [];
    encodeValue(bytes, record);
    return new Uint8Array(bytes);
  };
  const out_make_sample = new BigUint64Array(1);
  const sym_make_sample = sym("bffi_make_sample");
  const fn_make_sample = function (a0: TsOf<"number", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>, a2: TsOf<"string", typeof moduleJson>, a3: TsOf<"Axis", typeof moduleJson>): TsOf<"Sample", typeof moduleJson> {
    if (arguments.length !== 4) {
      throw new Error("make_sample: expected 4 argument(s), got " + arguments.length);
    }
    const wire_make_sample_axis = wireBytes("Axis", a3, "make_sample(axis)");
    const status = Number(sym_make_sample(a0, a1, a2, wire_make_sample_axis.length > 0 ? ptr(wire_make_sample_axis) : null, wire_make_sample_axis.length, out_make_sample));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_make_sample failed: " + String(status));
    }
    if (typeof ((out_make_sample[0] ?? 0n)) !== "bigint") {
      throw new TypeError("make_sample: expected a buffer handle");
    }
    const bytes_make_sample = readBuffer((out_make_sample[0] ?? 0n));
    return wireToJs(tables, "Sample", decodeAt(bytes_make_sample, 0).value, "make_sample()") as TsOf<"Sample", typeof moduleJson>;
  };
  const out_recenter = new BigUint64Array(1);
  const sym_recenter = sym("bffi_recenter");
  const fn_recenter = function (a0: TsOf<"Sample", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>): TsOf<"Sample", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("recenter: expected 2 argument(s), got " + arguments.length);
    }
    const wire_recenter_sample = wireBytes("Sample", a0, "recenter(sample)");
    const status = Number(sym_recenter(wire_recenter_sample.length > 0 ? ptr(wire_recenter_sample) : null, wire_recenter_sample.length, a1, out_recenter));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_recenter failed: " + String(status));
    }
    if (typeof ((out_recenter[0] ?? 0n)) !== "bigint") {
      throw new TypeError("recenter: expected a buffer handle");
    }
    const bytes_recenter = readBuffer((out_recenter[0] ?? 0n));
    return wireToJs(tables, "Sample", decodeAt(bytes_recenter, 0).value, "recenter()") as TsOf<"Sample", typeof moduleJson>;
  };
  const out_total_weight = new BigInt64Array(1);
  const sym_total_weight = sym("bffi_total_weight");
  const fn_total_weight = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("total_weight: expected 1 argument(s), got " + arguments.length);
    }
    const wire_total_weight_samples = wireBytes("Sample[]", a0, "total_weight(samples)");
    const status = Number(sym_total_weight(wire_total_weight_samples.length > 0 ? ptr(wire_total_weight_samples) : null, wire_total_weight_samples.length, out_total_weight));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_total_weight failed: " + String(status));
    }
    return (out_total_weight[0] ?? 0n);
  };
  const out_distances = new BigUint64Array(1);
  const sym_distances = sym("bffi_distances");
  const fn_distances = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"number[]", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("distances: expected 1 argument(s), got " + arguments.length);
    }
    const wire_distances_samples = wireBytes("Sample[]", a0, "distances(samples)");
    const status = Number(sym_distances(wire_distances_samples.length > 0 ? ptr(wire_distances_samples) : null, wire_distances_samples.length, out_distances));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_distances failed: " + String(status));
    }
    if (typeof ((out_distances[0] ?? 0n)) !== "bigint") {
      throw new TypeError("distances: expected a buffer handle");
    }
    const bytes_distances = readBuffer((out_distances[0] ?? 0n));
    return wireToJs(tables, "number[]", decodeAt(bytes_distances, 0).value, "distances()") as TsOf<"number[]", typeof moduleJson>;
  };
  const out_labels = new BigUint64Array(1);
  const sym_labels = sym("bffi_labels");
  const fn_labels = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"string[]", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("labels: expected 1 argument(s), got " + arguments.length);
    }
    const wire_labels_samples = wireBytes("Sample[]", a0, "labels(samples)");
    const status = Number(sym_labels(wire_labels_samples.length > 0 ? ptr(wire_labels_samples) : null, wire_labels_samples.length, out_labels));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_labels failed: " + String(status));
    }
    if (typeof ((out_labels[0] ?? 0n)) !== "bigint") {
      throw new TypeError("labels: expected a buffer handle");
    }
    const bytes_labels = readBuffer((out_labels[0] ?? 0n));
    return wireToJs(tables, "string[]", decodeAt(bytes_labels, 0).value, "labels()") as TsOf<"string[]", typeof moduleJson>;
  };
  const out_label_bytes = new BigUint64Array(1);
  const sym_label_bytes = sym("bffi_label_bytes");
  const fn_label_bytes = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"Uint8Array[]", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("label_bytes: expected 1 argument(s), got " + arguments.length);
    }
    const wire_label_bytes_samples = wireBytes("Sample[]", a0, "label_bytes(samples)");
    const status = Number(sym_label_bytes(wire_label_bytes_samples.length > 0 ? ptr(wire_label_bytes_samples) : null, wire_label_bytes_samples.length, out_label_bytes));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_label_bytes failed: " + String(status));
    }
    if (typeof ((out_label_bytes[0] ?? 0n)) !== "bigint") {
      throw new TypeError("label_bytes: expected a buffer handle");
    }
    const bytes_label_bytes = readBuffer((out_label_bytes[0] ?? 0n));
    return wireToJs(tables, "Uint8Array[]", decodeAt(bytes_label_bytes, 0).value, "label_bytes()") as TsOf<"Uint8Array[]", typeof moduleJson>;
  };
  const out_heaviest = new BigUint64Array(1);
  const sym_heaviest = sym("bffi_heaviest");
  const fn_heaviest = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"Sample | null", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("heaviest: expected 1 argument(s), got " + arguments.length);
    }
    const wire_heaviest_samples = wireBytes("Sample[]", a0, "heaviest(samples)");
    const status = Number(sym_heaviest(wire_heaviest_samples.length > 0 ? ptr(wire_heaviest_samples) : null, wire_heaviest_samples.length, out_heaviest));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_heaviest failed: " + String(status));
    }
    if (typeof ((out_heaviest[0] ?? 0n)) !== "bigint") {
      throw new TypeError("heaviest: expected a buffer handle");
    }
    if ((out_heaviest[0] ?? 0n) === 0n) {
      return null;
    }
    const bytes_heaviest = readBuffer((out_heaviest[0] ?? 0n));
    return wireToJs(tables, "Sample", decodeAt(bytes_heaviest, 0).value, "heaviest()") as TsOf<"Sample | null", typeof moduleJson>;
  };
  const out_classify = new BigUint64Array(1);
  const sym_classify = sym("bffi_classify");
  const fn_classify = function (a0: TsOf<"Sample[]", typeof moduleJson>): TsOf<"Axis", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("classify: expected 1 argument(s), got " + arguments.length);
    }
    const wire_classify_samples = wireBytes("Sample[]", a0, "classify(samples)");
    const status = Number(sym_classify(wire_classify_samples.length > 0 ? ptr(wire_classify_samples) : null, wire_classify_samples.length, out_classify));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_classify failed: " + String(status));
    }
    if (typeof ((out_classify[0] ?? 0n)) !== "bigint") {
      throw new TypeError("classify: expected a buffer handle");
    }
    const bytes_classify = readBuffer((out_classify[0] ?? 0n));
    return wireToJs(tables, "Axis", decodeAt(bytes_classify, 0).value, "classify()") as TsOf<"Axis", typeof moduleJson>;
  };
  const out_echo_profile = new BigUint64Array(1);
  const sym_echo_profile = sym("bffi_echo_profile");
  const fn_echo_profile = function (a0: TsOf<"Profile", typeof moduleJson>): TsOf<"Profile", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("echo_profile: expected 1 argument(s), got " + arguments.length);
    }
    const wire_echo_profile_profile = wireBytes("Profile", a0, "echo_profile(profile)");
    const status = Number(sym_echo_profile(wire_echo_profile_profile.length > 0 ? ptr(wire_echo_profile_profile) : null, wire_echo_profile_profile.length, out_echo_profile));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_echo_profile failed: " + String(status));
    }
    if (typeof ((out_echo_profile[0] ?? 0n)) !== "bigint") {
      throw new TypeError("echo_profile: expected a buffer handle");
    }
    const bytes_echo_profile = readBuffer((out_echo_profile[0] ?? 0n));
    return wireToJs(tables, "Profile", decodeAt(bytes_echo_profile, 0).value, "echo_profile()") as TsOf<"Profile", typeof moduleJson>;
  };
  return {
    "make_sample": fn_make_sample,
    "recenter": fn_recenter,
    "total_weight": fn_total_weight,
    "distances": fn_distances,
    "labels": fn_labels,
    "label_bytes": fn_label_bytes,
    "heaviest": fn_heaviest,
    "classify": fn_classify,
    "echo_profile": fn_echo_profile,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
