// @generated by bffi codegen - do not edit.
// Source module: api

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "api",
  "functions": [
    {
      "name": "add",
      "export": "bffi_add",
      "docs": [
        "Adds two numbers."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "shout",
      "export": "bffi_shout",
      "docs": [],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "compute",
      "export": "bffi_compute",
      "docs": [
        "Async compute."
      ],
      "params": [
        {
          "name": "x",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "Promise<number>",
        "abi": "task"
      },
      "out": "handle"
    }
  ],
  "classes": [
    {
      "name": "counter",
      "release": "bffi_counter_release",
      "docs": [
        "A native counter."
      ],
      "constructor": {
        "name": "constructor",
        "export": "bffi_counter_new",
        "docs": [
          "Creates a counter."
        ],
        "params": [
          {
            "name": "start",
            "ts": "number",
            "abi": "u32"
          }
        ],
        "ret": {
          "ts": "bigint",
          "abi": "handle"
        },
        "out": "handle"
      },
      "fields": [
        {
          "name": "value",
          "export": "bffi_counter_value_get",
          "docs": [
            "The current value."
          ],
          "ts": "number",
          "out": "u32"
        }
      ],
      "methods": [
        {
          "name": "increment",
          "export": "bffi_counter_increment",
          "docs": [],
          "params": [],
          "ret": {
            "ts": "number",
            "abi": "u32"
          },
          "out": "u32"
        }
      ]
    }
  ],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
