// @generated by bffi codegen - do not edit.
// Source module: api
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeUtf8,
  makeReadBuffer,
  makeRelease,
  makeTakeError,
  wrapTask,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "api",
  "abiVersion": 1,
  "functions": [
    {
      "name": "add",
      "export": "bffi_add",
      "docs": [
        "Adds two numbers."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "shout",
      "export": "bffi_shout",
      "docs": [],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "compute",
      "export": "bffi_compute",
      "docs": [
        "Async compute."
      ],
      "params": [
        {
          "name": "x",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "Promise<number>",
        "abi": "task"
      },
      "out": "handle"
    }
  ],
  "classes": [
    {
      "name": "counter",
      "release": "bffi_counter_release",
      "docs": [
        "A native counter."
      ],
      "constructor": {
        "name": "constructor",
        "export": "bffi_counter_new",
        "docs": [
          "Creates a counter."
        ],
        "params": [
          {
            "name": "start",
            "ts": "number",
            "abi": "u32"
          }
        ],
        "ret": {
          "ts": "bigint",
          "abi": "handle"
        },
        "out": "handle"
      },
      "fields": [
        {
          "name": "value",
          "export": "bffi_counter_value_get",
          "docs": [
            "The current value."
          ],
          "ts": "number",
          "out": "u32"
        }
      ],
      "methods": [
        {
          "name": "increment",
          "export": "bffi_counter_increment",
          "docs": [],
          "params": [],
          "ret": {
            "ts": "number",
            "abi": "u32"
          },
          "out": "u32"
        }
      ]
    }
  ],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_add = new Uint32Array(1);
  const sym_add = sym("bffi_add");
  const fn_add = function (a0: TsOf<"number", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("add: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_add(a0, a1, out_add));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_add failed: " + String(status));
    }
    return (out_add[0] ?? 0);
  };
  const out_shout = new BigUint64Array(1);
  const sym_shout = sym("bffi_shout");
  const fn_shout = function (a0: TsOf<"string", typeof moduleJson>): TsOf<"string", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("shout: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_shout(a0, out_shout));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_shout failed: " + String(status));
    }
    if (typeof ((out_shout[0] ?? 0n)) !== "bigint") {
      throw new TypeError("shout: expected a buffer handle");
    }
    const bytes_shout = readBuffer((out_shout[0] ?? 0n));
    return decodeUtf8(bytes_shout);
  };
  const out_compute = new BigUint64Array(1);
  const sym_compute = sym("bffi_compute");
  const fn_compute = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"Promise<number>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("compute: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_compute(a0, out_compute));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_compute failed: " + String(status));
    }
    if (typeof ((out_compute[0] ?? 0n)) !== "bigint") {
      throw new TypeError("compute: expected a task handle");
    }
    return wrapTask(lib, (out_compute[0] ?? 0n), "Promise<number>", moduleJson) as unknown as TsOf<"Promise<number>", typeof moduleJson>;
  };
  const out_counter_constructor = new BigUint64Array(1);
  const sym_counter_constructor = sym("bffi_counter_new");
  const out_counter_value = new Uint32Array(1);
  const sym_counter_value = sym("bffi_counter_value_get");
  const out_counter_increment = new Uint32Array(1);
  const sym_counter_increment = sym("bffi_counter_increment");
  const release_counter = makeRelease(lib, "bffi_counter_release", takeError);
  const finalizers_counter = new FinalizationRegistry((handle: bigint): void => {
    release_counter(handle);
  });
  const cls_counter = class {
    handle: bigint;
    [Symbol.dispose](): void {
      this.release();
    }
    constructor(a0: TsOf<"number", typeof moduleJson>) {
      if (arguments.length !== 1) {
        throw new Error("counter constructor: expected 1 argument(s), got " + arguments.length);
      }
      const status = Number(sym_counter_constructor(a0, out_counter_constructor));
      if (status !== ErrorCode.Ok) {
        const error = takeError(status);
        throw error ?? new Error("bffi_counter_new failed: " + String(status));
      }
      this.handle = (out_counter_constructor[0] ?? 0n);
      finalizers_counter.register(this, this.handle);
    }
    release(): void {
      finalizers_counter.unregister(this);
      release_counter(this.handle);
    }
    get value(): TsOf<"number", typeof moduleJson> {
      const status = Number(sym_counter_value(this.handle, out_counter_value));
      if (status !== ErrorCode.Ok) {
        const error = takeError(status);
        throw error ?? new Error("bffi_counter_value_get failed: " + String(status));
      }
      return (out_counter_value[0] ?? 0);
    }
    increment(): TsOf<"number", typeof moduleJson> {
      if (arguments.length !== 0) {
        throw new Error("counter.increment: expected 0 argument(s), got " + arguments.length);
      }
      const status = Number(sym_counter_increment(this.handle, out_counter_increment));
      if (status !== ErrorCode.Ok) {
        const error = takeError(status);
        throw error ?? new Error("bffi_counter_increment failed: " + String(status));
      }
      return (out_counter_increment[0] ?? 0);
    }
  };
  return {
    "add": fn_add,
    "shout": fn_shout,
    "compute": fn_compute,
    "counter": cls_counter,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
