// @generated by bffi codegen - do not edit.
// Source module: native
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeUtf8,
  makeReadBuffer,
  makeTakeError,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "native",
  "abiVersion": 1,
  "exportsHash": "5615720039364060773",
  "functions": [
    {
      "name": "add",
      "export": "bffi_add",
      "docs": [
        "Adds two numbers."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "shout",
      "export": "bffi_shout",
      "docs": [
        "Returns an uppercased greeting (string return through the",
        "transient-buffer pair)."
      ],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "version",
      "export": "bffi_version",
      "docs": [
        "The version of this library (static string return)."
      ],
      "params": [],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_add = new Uint32Array(1);
  const sym_add = sym("bffi_add");
  const fn_add = function (a0: TsOf<"number", typeof moduleJson>, a1: TsOf<"number", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("add: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_add(a0, a1, out_add));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_add failed: " + String(status));
    }
    return (out_add[0] ?? 0);
  };
  const out_shout = new BigUint64Array(1);
  const sym_shout = sym("bffi_shout");
  const fn_shout = function (a0: TsOf<"string", typeof moduleJson>): TsOf<"string", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("shout: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_shout(a0, out_shout));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_shout failed: " + String(status));
    }
    if (typeof ((out_shout[0] ?? 0n)) !== "bigint") {
      throw new TypeError("shout: expected a buffer handle");
    }
    const bytes_shout = readBuffer((out_shout[0] ?? 0n));
    return decodeUtf8(bytes_shout);
  };
  const out_version = new BigUint64Array(1);
  const sym_version = sym("bffi_version");
  const fn_version = function (): TsOf<"string", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("version: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_version(out_version));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_version failed: " + String(status));
    }
    if (typeof ((out_version[0] ?? 0n)) !== "bigint") {
      throw new TypeError("version: expected a buffer handle");
    }
    const bytes_version = readBuffer((out_version[0] ?? 0n));
    return decodeUtf8(bytes_version);
  };
  return {
    "add": fn_add,
    "shout": fn_shout,
    "version": fn_version,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
