// @generated by bffi codegen - do not edit.
// Source module: streams
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  makeTakeError,
  streamItemTs,
  wrapStream,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "streams",
  "abiVersion": 1,
  "exportsHash": "13590191551223488418",
  "functions": [
    {
      "name": "numbers",
      "export": "bffi_numbers",
      "docs": [
        "Streams `1..=count` (an empty or huge count behaves as written)."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<number>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "samples",
      "export": "bffi_samples",
      "docs": [
        "Streams `count` alternating-axis samples."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<Sample>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "fizzbuzz",
      "export": "bffi_fizzbuzz",
      "docs": [
        "The classic transform: items of `1..=count` mapped to their",
        "fizzbuzz word (a stream of strings)."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<string>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "readings",
      "export": "bffi_readings",
      "docs": [
        "A slow PUSH producer: one reading per 5 ms tick, delivered with",
        "backpressure through the bounded buffer. JS pulls with",
        "`for await` exactly like the pull streams above."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<number>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "checked_readings",
      "export": "bffi_checked_readings",
      "docs": [
        "A PUSH producer delivering `Result` items: even ticks arrive as",
        "values, odd ticks as item errors (`ctx.push(Ok/Err)` - the item",
        "itself carries the domain outcome, the stream still completes)."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<number | Error>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "flaky",
      "export": "bffi_flaky",
      "docs": [
        "Result items: even indexes arrive as values, odd ones as item",
        "errors (the JS iterator throws at the first error item). The",
        "parens are the documented workaround for generic bindings in",
        "impl-trait position."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<bigint | Error>",
        "abi": "stream"
      },
      "out": "handle"
    },
    {
      "name": "big_values",
      "export": "bffi_big_values",
      "docs": [
        "Values descending from the u64 maximum (exact BigInt delivery)."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "AsyncIterableIterator<bigint>",
        "abi": "stream"
      },
      "out": "handle"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "Sample",
      "docs": [
        "One stream item."
      ],
      "fields": [
        {
          "name": "at",
          "docs": [
            "Where it was taken."
          ],
          "ts": "number"
        },
        {
          "name": "label",
          "docs": [
            "The station label."
          ],
          "ts": "string"
        },
        {
          "name": "axis",
          "docs": [
            "The axis it was taken along."
          ],
          "ts": "Axis"
        }
      ]
    }
  ],
  "enums": [
    {
      "name": "Axis",
      "docs": [
        "The measurement axis."
      ],
      "variants": [
        {
          "name": "Horizontal",
          "docs": [
            "Along the X axis."
          ]
        },
        {
          "name": "Vertical",
          "docs": [
            "Along the Y axis."
          ]
        }
      ]
    }
  ],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_numbers = new BigUint64Array(1);
  const sym_numbers = sym("bffi_numbers");
  const stream_item_numbers = streamItemTs("AsyncIterableIterator<number>");
  if (stream_item_numbers === null) {
    throw new Error("numbers: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<number>");
  }
  const fn_numbers = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<number>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("numbers: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_numbers(a0, out_numbers));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_numbers failed: " + String(status));
    }
    if (typeof ((out_numbers[0] ?? 0n)) !== "bigint") {
      throw new TypeError("numbers: expected a stream handle");
    }
    return wrapStream(lib, (out_numbers[0] ?? 0n), stream_item_numbers, moduleJson) as unknown as TsOf<"AsyncIterableIterator<number>", typeof moduleJson>;
  };
  const out_samples = new BigUint64Array(1);
  const sym_samples = sym("bffi_samples");
  const stream_item_samples = streamItemTs("AsyncIterableIterator<Sample>");
  if (stream_item_samples === null) {
    throw new Error("samples: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<Sample>");
  }
  const fn_samples = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<Sample>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("samples: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_samples(a0, out_samples));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_samples failed: " + String(status));
    }
    if (typeof ((out_samples[0] ?? 0n)) !== "bigint") {
      throw new TypeError("samples: expected a stream handle");
    }
    return wrapStream(lib, (out_samples[0] ?? 0n), stream_item_samples, moduleJson) as unknown as TsOf<"AsyncIterableIterator<Sample>", typeof moduleJson>;
  };
  const out_fizzbuzz = new BigUint64Array(1);
  const sym_fizzbuzz = sym("bffi_fizzbuzz");
  const stream_item_fizzbuzz = streamItemTs("AsyncIterableIterator<string>");
  if (stream_item_fizzbuzz === null) {
    throw new Error("fizzbuzz: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<string>");
  }
  const fn_fizzbuzz = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<string>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("fizzbuzz: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_fizzbuzz(a0, out_fizzbuzz));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_fizzbuzz failed: " + String(status));
    }
    if (typeof ((out_fizzbuzz[0] ?? 0n)) !== "bigint") {
      throw new TypeError("fizzbuzz: expected a stream handle");
    }
    return wrapStream(lib, (out_fizzbuzz[0] ?? 0n), stream_item_fizzbuzz, moduleJson) as unknown as TsOf<"AsyncIterableIterator<string>", typeof moduleJson>;
  };
  const out_readings = new BigUint64Array(1);
  const sym_readings = sym("bffi_readings");
  const stream_item_readings = streamItemTs("AsyncIterableIterator<number>");
  if (stream_item_readings === null) {
    throw new Error("readings: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<number>");
  }
  const fn_readings = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<number>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("readings: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_readings(a0, out_readings));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_readings failed: " + String(status));
    }
    if (typeof ((out_readings[0] ?? 0n)) !== "bigint") {
      throw new TypeError("readings: expected a stream handle");
    }
    return wrapStream(lib, (out_readings[0] ?? 0n), stream_item_readings, moduleJson) as unknown as TsOf<"AsyncIterableIterator<number>", typeof moduleJson>;
  };
  const out_checked_readings = new BigUint64Array(1);
  const sym_checked_readings = sym("bffi_checked_readings");
  const stream_item_checked_readings = streamItemTs("AsyncIterableIterator<number | Error>");
  if (stream_item_checked_readings === null) {
    throw new Error("checked_readings: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<number | Error>");
  }
  const fn_checked_readings = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<number | Error>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("checked_readings: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_checked_readings(a0, out_checked_readings));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_checked_readings failed: " + String(status));
    }
    if (typeof ((out_checked_readings[0] ?? 0n)) !== "bigint") {
      throw new TypeError("checked_readings: expected a stream handle");
    }
    return wrapStream(lib, (out_checked_readings[0] ?? 0n), stream_item_checked_readings, moduleJson) as unknown as TsOf<"AsyncIterableIterator<number | Error>", typeof moduleJson>;
  };
  const out_flaky = new BigUint64Array(1);
  const sym_flaky = sym("bffi_flaky");
  const stream_item_flaky = streamItemTs("AsyncIterableIterator<bigint | Error>");
  if (stream_item_flaky === null) {
    throw new Error("flaky: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<bigint | Error>");
  }
  const fn_flaky = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<bigint | Error>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("flaky: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_flaky(a0, out_flaky));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_flaky failed: " + String(status));
    }
    if (typeof ((out_flaky[0] ?? 0n)) !== "bigint") {
      throw new TypeError("flaky: expected a stream handle");
    }
    return wrapStream(lib, (out_flaky[0] ?? 0n), stream_item_flaky, moduleJson) as unknown as TsOf<"AsyncIterableIterator<bigint | Error>", typeof moduleJson>;
  };
  const out_big_values = new BigUint64Array(1);
  const sym_big_values = sym("bffi_big_values");
  const stream_item_big_values = streamItemTs("AsyncIterableIterator<bigint>");
  if (stream_item_big_values === null) {
    throw new Error("big_values: stream return type must be AsyncIterableIterator<T>, got AsyncIterableIterator<bigint>");
  }
  const fn_big_values = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"AsyncIterableIterator<bigint>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("big_values: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_big_values(a0, out_big_values));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_big_values failed: " + String(status));
    }
    if (typeof ((out_big_values[0] ?? 0n)) !== "bigint") {
      throw new TypeError("big_values: expected a stream handle");
    }
    return wrapStream(lib, (out_big_values[0] ?? 0n), stream_item_big_values, moduleJson) as unknown as TsOf<"AsyncIterableIterator<bigint>", typeof moduleJson>;
  };
  return {
    "numbers": fn_numbers,
    "samples": fn_samples,
    "fizzbuzz": fn_fizzbuzz,
    "readings": fn_readings,
    "checked_readings": fn_checked_readings,
    "flaky": fn_flaky,
    "big_values": fn_big_values,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
