//! `extern "C"` shim codegen under the boundary policy (DESIGN §6.1,
//! §6.3, §6.5).
//!
//! [`expand`] renders exactly one shim per validated function: the
//! symbol the JS side links against (`bffi_<name>`). The shim copies
//! inputs (never zero-copy), validates every pointer, validates UTF-8
//! on the cstring path, and transports the result through an
//! out-parameter, returning an [`ErrorCode`]-style status from
//! `bffi-core`. Panics follow the per-build policy: debug builds let
//! the panic escape (the process aborts, easier debugging), release
//! builds run the body through `bffi_core::boundary::run_extern_body`,
//! which converts the panic into `ErrorCode::Panic` plus a stored
//! thread-local last error.
//!
//! The transport-level token generators (out-parameters, return tails,
//! cstring conversions) live in `crate::support::codegen`; this
//! module assembles them into the `#[bffi]`-specific shim pair.

use crate::model::FnModel;
use crate::support::codegen::{
    has_out, out_param, param_conversions, param_ident, ret_body, shim_param,
};
use crate::support::kind::ShimKind;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Renders the shim expansion of a validated model: the pair of cfg
/// variants for the symbol the JS side links against
/// (`bffi_<name>`). The caller assembles the full expansion
/// (original item, shims, descriptor).
pub(crate) fn expand(model: &FnModel) -> TokenStream {
    let core = &model.paths.core;
    let shim_ident = format_ident!("bffi_{}", model.ident);
    // The doc attribute keeps the generated symbol usable in crates
    // with the framework's `missing_docs` lint set.
    let shim_doc = format!("C ABI shim for `{}` (generated by `#[bffi]`).", model.ident);
    let params: Vec<TokenStream> = model
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| shim_param(&param.name, param.kind.clone(), index))
        .collect();
    let out = out_param(&model.ret);
    let body = body(model);

    // Variant A (dev): the body runs directly - a panic escapes and
    // aborts, which keeps stack traces intact while debugging
    // (DESIGN §6.5).
    let debug_shim = quote! {
        #[cfg(debug_assertions)]
        #[unsafe(no_mangle)]
        #[doc = #shim_doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #shim_ident(#(#params,)* #(#out)*) -> u32 {
            #body
        }
    };
    // Variant B (prod): the entire body runs inside the boundary
    // policy, so a panic becomes `ErrorCode::Panic` plus a stored last
    // error instead of unwinding into the host.
    let release_shim = quote! {
        #[cfg(not(debug_assertions))]
        #[unsafe(no_mangle)]
        #[doc = #shim_doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #shim_ident(#(#params,)* #(#out)*) -> u32 {
            #core::boundary::run_extern_body_u32(move || { #body })
        }
    };

    quote! { #debug_shim #release_shim }
}

/// Renders the shim body shared by both cfg variants: pointer
/// validation first, the borrowed-parameter conversion per `&str` /
/// `&[u8]` parameter, then the call and the out-parameter write.
fn body(model: &FnModel) -> TokenStream {
    let core = &model.paths.core;
    let mut body = TokenStream::new();

    if has_out(&model.ret) {
        body.extend(quote! {
            if __ret.is_null() {
                let error = #core::BffiError::new(
                    #core::ErrorCode::NullPointer,
                    "output pointer is null",
                );
                #core::set_last_error(error);
                return #core::ErrorCode::NullPointer.as_u32();
            }
        });
    }

    body.extend(param_conversions(
        &model.paths,
        model
            .params
            .iter()
            .map(|param| (param.name.as_str(), param.kind.clone())),
    ));

    let ident = &model.ident;
    let args = model.params.iter().enumerate().map(|(index, param)| {
        let name = param_ident(&param.name, index);
        match &param.kind {
            // `ZeroCopyStr` derefs to `str`.
            ShimKind::Str => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            // `ZeroCopyBuf` derefs to `[u8]`.
            ShimKind::BufferView => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            // Records and sequences decode into the owned local named
            // `#name` in the conversion preamble; optional parameters
            // bind their `Option<..>` local the same way.
            ShimKind::Prim(_)
            | ShimKind::BigInt(_)
            | ShimKind::Record(_)
            | ShimKind::Seq(_)
            | ShimKind::Opt(_) => {
                quote! { #name }
            }
        }
    });
    let call = quote! { #ident(#(#args,)*) };

    body.extend(ret_body(&model.paths, &model.ret, call));
    body
}

#[cfg(test)]
mod tests {
    use super::expand;
    use crate::model::FnModel;
    use crate::support::codegen::param_ident;
    use quote::quote;

    #[test]
    fn wildcard_pattern_name_falls_back_to_positional() {
        assert_eq!(param_ident("_", 2).to_string(), "__arg2");
    }

    #[test]
    fn valid_ident_passes_through() {
        assert_eq!(param_ident("phrase", 0).to_string(), "phrase");
    }

    #[test]
    fn keyword_falls_back_to_positional() {
        assert_eq!(param_ident("fn", 1).to_string(), "__arg1");
    }

    #[test]
    fn expansion_adds_both_cfg_shims_without_the_item() {
        let item = quote! {
            /// Adds two numbers.
            fn add(a: u32, b: u32) -> u32 {
                a + b
            }
        };
        let attrs = proc_macro2::TokenStream::new();
        let model = FnModel::parse(&attrs, item).expect("accepted");

        let tokens = expand(&model).to_string();

        assert!(
            !tokens.contains("fn add "),
            "the original item is echoed by the entry, not the shim generator"
        );
        assert!(
            !tokens.contains("Adds two numbers"),
            "docs stay on the echoed item"
        );
        assert!(tokens.contains("fn bffi_add"));
        assert!(tokens.contains("no_mangle"));
        assert!(
            tokens.contains("cfg (debug_assertions)"),
            "exactly one dev variant"
        );
        assert!(
            tokens.contains("cfg (not (debug_assertions))"),
            "exactly one release variant"
        );
        assert!(tokens.contains("run_extern_body"));
        assert!(tokens.contains("not_unsafe_ptr_arg_deref"));
        assert!(tokens.contains("NullPointer"));
    }
}
