// @generated by bffi codegen - do not edit.
// Source module: async
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  makeTakeError,
  wrapTask,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "async",
  "functions": [
    {
      "name": "double_async",
      "export": "bffi_double_async",
      "docs": [
        "Doubles `x` after a short sleep: the `#[bffi_async]` macro turns",
        "this into a spawn shim returning a task handle; JS awaits",
        "`Promise<bigint>`."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "Promise<bigint>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "shout_async",
      "export": "bffi_shout_async",
      "docs": [
        "Returns an uppercased greeting: string results are delivered",
        "through the transient-buffer payload (the same transport as the",
        "sync `String` returns, encoded into the wire record)."
      ],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "Promise<string>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "report_async",
      "export": "bffi_report_async",
      "docs": [
        "Builds a report after a short sleep: composite results ride the",
        "wire channel (`Promise<Report>` on the JS side, decoded through",
        "the module's record table)."
      ],
      "params": [
        {
          "name": "value",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "Promise<Report>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "ticks_async",
      "export": "bffi_ticks_async",
      "docs": [
        "Collects a number sequence: `Vec<T>` async returns ride the same",
        "wire channel as sequences (`Promise<number[]>` on the JS side)."
      ],
      "params": [
        {
          "name": "count",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "Promise<number[]>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "maybe_report",
      "export": "bffi_maybe_report",
      "docs": [
        "An optional report: `None` (zero value) arrives as `null` - the",
        "`Option<Report>` async return (`Promise<Report | null>`)."
      ],
      "params": [
        {
          "name": "value",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "Promise<Report | null>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "fail_async",
      "export": "bffi_fail_async",
      "docs": [
        "A failing task: `Result` rejects the promise with the domain",
        "message."
      ],
      "params": [],
      "ret": {
        "ts": "Promise<bigint>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "panic_async",
      "export": "bffi_panic_async",
      "docs": [
        "A panicking task: the executor's `catch_unwind` converts the panic",
        "into a rejection with the panic message."
      ],
      "params": [],
      "ret": {
        "ts": "Promise<bigint>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "timed_async",
      "export": "bffi_timed_async",
      "docs": [
        "A task that never completes on its own: a 50 ms deadline drops the",
        "inner future and rejects the promise with \"task timed out\"."
      ],
      "params": [],
      "ret": {
        "ts": "Promise<bigint>",
        "abi": "task"
      },
      "out": "handle"
    },
    {
      "name": "spawn_slow",
      "export": "bffi_spawn_slow",
      "docs": [
        "Spawns a slow task by hand (no macro): the RAW task handle comes",
        "back as a plain `u64`, so JS can cancel it through [`cancel_task`]",
        "before wrapping it into a promise with `wrapTask`."
      ],
      "params": [
        {
          "name": "ms",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "cancel_task",
      "export": "bffi_cancel_task",
      "docs": [
        "Requests cooperative cancellation of a task: `1` = a running task",
        "was cancelled (the attached promise rejects with \"task",
        "cancelled\"), `0` = invalid/stale handle or already finished."
      ],
      "params": [
        {
          "name": "task",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "async_pending",
      "export": "bffi_async_pending",
      "docs": [
        "The number of spawned-but-unfinished tasks (a probe for tests)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "Drains the event loop without blocking: the JS side calls this in",
        "a loop (`pumpUntil` from `@z2net/bffi`) while a task promise is",
        "pending - the resolution job executes on the JS thread during the",
        "drain, and THAT is what settles the promise."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "Report",
      "docs": [
        "A task's final report (delivered as `Promise<Report>` on the JS",
        "side)."
      ],
      "fields": [
        {
          "name": "value",
          "docs": [
            "The computed value."
          ],
          "ts": "bigint"
        },
        {
          "name": "label",
          "docs": [
            "A human-readable label."
          ],
          "ts": "string"
        }
      ]
    }
  ],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_double_async = new BigUint64Array(1);
  const sym_double_async = sym("bffi_double_async");
  const fn_double_async = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"Promise<bigint>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("double_async: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_double_async(a0, out_double_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_double_async failed: " + String(status));
    }
    if (typeof ((out_double_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("double_async: expected a task handle");
    }
    return wrapTask(lib, (out_double_async[0] ?? 0n), "Promise<bigint>", moduleJson) as unknown as TsOf<"Promise<bigint>", typeof moduleJson>;
  };
  const out_shout_async = new BigUint64Array(1);
  const sym_shout_async = sym("bffi_shout_async");
  const fn_shout_async = function (a0: TsOf<"string", typeof moduleJson>): TsOf<"Promise<string>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("shout_async: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_shout_async(a0, out_shout_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_shout_async failed: " + String(status));
    }
    if (typeof ((out_shout_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("shout_async: expected a task handle");
    }
    return wrapTask(lib, (out_shout_async[0] ?? 0n), "Promise<string>", moduleJson) as unknown as TsOf<"Promise<string>", typeof moduleJson>;
  };
  const out_report_async = new BigUint64Array(1);
  const sym_report_async = sym("bffi_report_async");
  const fn_report_async = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"Promise<Report>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("report_async: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_report_async(a0, out_report_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_report_async failed: " + String(status));
    }
    if (typeof ((out_report_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("report_async: expected a task handle");
    }
    return wrapTask(lib, (out_report_async[0] ?? 0n), "Promise<Report>", moduleJson) as unknown as TsOf<"Promise<Report>", typeof moduleJson>;
  };
  const out_ticks_async = new BigUint64Array(1);
  const sym_ticks_async = sym("bffi_ticks_async");
  const fn_ticks_async = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"Promise<number[]>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("ticks_async: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_ticks_async(a0, out_ticks_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_ticks_async failed: " + String(status));
    }
    if (typeof ((out_ticks_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("ticks_async: expected a task handle");
    }
    return wrapTask(lib, (out_ticks_async[0] ?? 0n), "Promise<number[]>", moduleJson) as unknown as TsOf<"Promise<number[]>", typeof moduleJson>;
  };
  const out_maybe_report = new BigUint64Array(1);
  const sym_maybe_report = sym("bffi_maybe_report");
  const fn_maybe_report = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"Promise<Report | null>", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("maybe_report: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_maybe_report(a0, out_maybe_report));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_maybe_report failed: " + String(status));
    }
    if (typeof ((out_maybe_report[0] ?? 0n)) !== "bigint") {
      throw new TypeError("maybe_report: expected a task handle");
    }
    return wrapTask(lib, (out_maybe_report[0] ?? 0n), "Promise<Report | null>", moduleJson) as unknown as TsOf<"Promise<Report | null>", typeof moduleJson>;
  };
  const out_fail_async = new BigUint64Array(1);
  const sym_fail_async = sym("bffi_fail_async");
  const fn_fail_async = function (): TsOf<"Promise<bigint>", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("fail_async: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_fail_async(out_fail_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_fail_async failed: " + String(status));
    }
    if (typeof ((out_fail_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("fail_async: expected a task handle");
    }
    return wrapTask(lib, (out_fail_async[0] ?? 0n), "Promise<bigint>", moduleJson) as unknown as TsOf<"Promise<bigint>", typeof moduleJson>;
  };
  const out_panic_async = new BigUint64Array(1);
  const sym_panic_async = sym("bffi_panic_async");
  const fn_panic_async = function (): TsOf<"Promise<bigint>", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("panic_async: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_panic_async(out_panic_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_panic_async failed: " + String(status));
    }
    if (typeof ((out_panic_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("panic_async: expected a task handle");
    }
    return wrapTask(lib, (out_panic_async[0] ?? 0n), "Promise<bigint>", moduleJson) as unknown as TsOf<"Promise<bigint>", typeof moduleJson>;
  };
  const out_timed_async = new BigUint64Array(1);
  const sym_timed_async = sym("bffi_timed_async");
  const fn_timed_async = function (): TsOf<"Promise<bigint>", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("timed_async: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_timed_async(out_timed_async));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_timed_async failed: " + String(status));
    }
    if (typeof ((out_timed_async[0] ?? 0n)) !== "bigint") {
      throw new TypeError("timed_async: expected a task handle");
    }
    return wrapTask(lib, (out_timed_async[0] ?? 0n), "Promise<bigint>", moduleJson) as unknown as TsOf<"Promise<bigint>", typeof moduleJson>;
  };
  const out_spawn_slow = new BigUint64Array(1);
  const sym_spawn_slow = sym("bffi_spawn_slow");
  const fn_spawn_slow = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("spawn_slow: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_spawn_slow(a0, out_spawn_slow));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_spawn_slow failed: " + String(status));
    }
    return (out_spawn_slow[0] ?? 0n);
  };
  const out_cancel_task = new Uint32Array(1);
  const sym_cancel_task = sym("bffi_cancel_task");
  const fn_cancel_task = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("cancel_task: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_cancel_task(a0, out_cancel_task));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_cancel_task failed: " + String(status));
    }
    return (out_cancel_task[0] ?? 0);
  };
  const out_async_pending = new BigUint64Array(1);
  const sym_async_pending = sym("bffi_async_pending");
  const fn_async_pending = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("async_pending: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_async_pending(out_async_pending));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_async_pending failed: " + String(status));
    }
    return (out_async_pending[0] ?? 0n);
  };
  const out_loop_pump = new BigUint64Array(1);
  const sym_loop_pump = sym("bffi_loop_pump");
  const fn_loop_pump = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pump: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pump(out_loop_pump));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pump failed: " + String(status));
    }
    return (out_loop_pump[0] ?? 0n);
  };
  return {
    "double_async": fn_double_async,
    "shout_async": fn_shout_async,
    "report_async": fn_report_async,
    "ticks_async": fn_ticks_async,
    "maybe_report": fn_maybe_report,
    "fail_async": fn_fail_async,
    "panic_async": fn_panic_async,
    "timed_async": fn_timed_async,
    "spawn_slow": fn_spawn_slow,
    "cancel_task": fn_cancel_task,
    "async_pending": fn_async_pending,
    "loop_pump": fn_loop_pump,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
