//! The deterministic `.d.ts` renderer.
//!
//! Turns a [`ModuleDef`] into a complete TypeScript declaration file.
//! The renderer is pure: the output depends only on the IR, so
//! re-rendering the same module always yields byte-identical output
//! (see the "Render guarantees" section of the crate docs).

use super::ident::sanitize;
use super::ir::{ClassDef, EnumDef, FieldDef, FunctionDef, MethodDef, ModuleDef, RecordDef};

/// Renders `module` as a complete TypeScript declaration file.
///
/// # Format contract
///
/// The exact output format is:
///
/// 1. Line 1: `// @generated by bffi-dts - do not edit.`
/// 2. Line 2: `// Source module: {module.name}`
/// 3. For each record, in declaration order: one empty line, then
///    the interface block: the JSDoc block (same rules as
///    functions), `export interface {js_name} {`, one
///    `  {name}: {ty};` line per field (field JSDoc first, rendered
///    like class-member docs), and a closing `}` line.
/// 4. For each enum, in declaration order: one empty line, then
///    `export type {js_name} = "A" | "B";` - the variant names as a
///    string-literal union, sanitized, in declaration order (the
///    enum-level JSDoc renders first; per-variant docs are part of
///    the IR but not of the one-line union).
/// 5. For each function, in declaration order: one empty line, then
///    the function block consisting of
///    - a JSDoc comment, rendered only when [`FunctionDef::docs`] is
///      non-empty: a single doc line renders as `/** {line} */`; two
///      or more render as a `/**` opening line, one ` * {line}` line
///      per doc line, and a ` */` closing line;
///    - `export function {js_name}({params}): {ret};` where `js_name`
///      and every parameter name are passed through [`sanitize`],
///      parameters are joined by `, ` as `name: type`, and every type
///      name comes from [`TsType::as_str`] (so [`TsType::Void`] renders
///      `void` with no special casing).
/// 6. For each class, in declaration order: one empty line, then the
///    class block: the JSDoc block (same rules), then
///    `export class {js_name} {` / the constructor declaration
///    (`constructor({params});`, JSDoc first) / the field getters
///    (`get {name}(): {ty};`, JSDoc first) / the methods
///    (`{name}({params}): {ret};`, JSDoc first), each indented by two
///    spaces / a closing `}` line.
///
/// Records and enums render before functions and classes: types
/// precede their uses.
///
/// The output uses LF line endings throughout and ends with exactly
/// one trailing newline; a module with no functions and no classes
/// therefore ends right after its two header lines. No timestamps or
/// version numbers are embedded. `export_name` fields are never
/// rendered: they exist for the build side only.
///
/// # Panics
///
/// Never panics: all slices are iterated, never indexed, names are
/// sanitized through the total (infallible) [`sanitize`], and the file
/// is built with `push_str`/`push` alone.
#[must_use]
pub fn render(module: &ModuleDef) -> String {
    let mut out = String::new();
    out.push_str("// @generated by bffi-dts - do not edit.\n");
    out.push_str("// Source module: ");
    out.push_str(module.name);
    out.push('\n');
    for record in module.records {
        out.push('\n');
        push_record(record, &mut out);
    }
    for enumeration in module.enums {
        out.push('\n');
        push_enum(enumeration, &mut out);
    }
    for function in module.fns {
        out.push('\n');
        push_function(function, &mut out);
    }
    for class in module.classes {
        out.push('\n');
        push_class(class, &mut out);
    }
    out
}

/// Appends one record block: JSDoc header, `export interface` with
/// one `name: type;` line per field.
fn push_record(record: &RecordDef, out: &mut String) {
    push_docs(record.docs, out);
    out.push_str("export interface ");
    out.push_str(&sanitize(record.js_name));
    out.push_str(" {\n");
    for field in record.fields {
        push_member_docs(field.docs, out);
        out.push_str("  ");
        out.push_str(&sanitize(field.name));
        out.push_str(": ");
        out.push_str(&field.ty.as_str());
        out.push_str(";\n");
    }
    out.push_str("}\n");
}

/// Appends one enum block: a JSDoc header and either the
/// string-literal union of variant names (unit-only enums, one line)
/// or the discriminated union of `{ kind, ... }` objects (payload
/// variants carry their fields positionally after the `kind`
/// discriminant).
fn push_enum(enumeration: &EnumDef, out: &mut String) {
    push_docs(enumeration.docs, out);
    out.push_str("export type ");
    out.push_str(&sanitize(enumeration.js_name));
    let has_payload = enumeration
        .variants
        .iter()
        .any(|variant| !variant.fields.is_empty());
    if !has_payload {
        out.push_str(" = ");
        let mut first = true;
        for variant in enumeration.variants {
            if !first {
                out.push_str(" | ");
            }
            first = false;
            out.push('"');
            out.push_str(&sanitize(variant.name));
            out.push('"');
        }
        out.push_str(";\n");
        return;
    }
    out.push_str(" =\n");
    for variant in enumeration.variants {
        out.push_str("  | ");
        out.push_str("{ kind: \"");
        out.push_str(&sanitize(variant.name));
        out.push('"');
        for field in variant.fields {
            out.push_str("; ");
            out.push_str(&sanitize(field.name));
            out.push_str(": ");
            out.push_str(&field.ty.as_str());
        }
        out.push_str(" }");
        out.push('\n');
    }
    out.push(';');
    out.push('\n');
}

/// Appends one function block: JSDoc (when docs are present) followed
/// by the `export function` declaration.
fn push_function(function: &FunctionDef, out: &mut String) {
    push_docs(function.docs, out);
    out.push_str("export function ");
    out.push_str(&sanitize(function.js_name));
    out.push('(');
    push_params(function.params, out);
    out.push_str("): ");
    out.push_str(&function.ret.as_str());
    out.push_str(";\n");
}

/// Appends one class block: the JSDoc header, then `export class` with
/// the constructor, field getters and methods indented inside.
fn push_class(class: &ClassDef, out: &mut String) {
    push_docs(class.docs, out);
    out.push_str("export class ");
    out.push_str(&sanitize(class.js_name));
    out.push_str(" {\n");
    push_method("constructor", &class.constructor, out);
    for field in class.fields {
        push_field(field, out);
    }
    for method in class.methods {
        push_method(&sanitize(method.js_name), method, out);
    }
    out.push_str("}\n");
}

/// Appends one constructor/method declaration line (two-space indent).
fn push_method(keyword: &str, method: &MethodDef, out: &mut String) {
    push_member_docs(method.docs, out);
    out.push_str("  ");
    out.push_str(keyword);
    out.push('(');
    push_params(method.params, out);
    out.push(')');
    if keyword != "constructor" {
        out.push_str(": ");
        out.push_str(&method.ret.as_str());
    }
    out.push_str(";\n");
}

/// Appends one read-only getter declaration line (two-space indent).
fn push_field(field: &FieldDef, out: &mut String) {
    push_member_docs(field.docs, out);
    out.push_str("  get ");
    out.push_str(&sanitize(field.js_name));
    out.push_str("(): ");
    out.push_str(&field.ty.as_str());
    out.push_str(";\n");
}

/// Appends `, `-joined `name: type` parameters.
fn push_params(params: &[super::ir::ParamDef], out: &mut String) {
    let mut first = true;
    for param in params {
        if !first {
            out.push_str(", ");
        }
        first = false;
        out.push_str(&sanitize(param.name));
        out.push_str(": ");
        out.push_str(&param.ty.as_str());
    }
}

/// Appends the JSDoc block for `docs`, or nothing when `docs` is
/// empty: one line renders inline, two or more render as a block.
fn push_docs(docs: &[&str], out: &mut String) {
    if let [only] = docs {
        out.push_str("/** ");
        out.push_str(only);
        out.push_str(" */\n");
        return;
    }
    if docs.is_empty() {
        return;
    }
    out.push_str("/**\n");
    for line in docs {
        out.push_str(" * ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(" */\n");
}

/// The JSDoc renderer for class members: every rendered line gets the
/// two-space body indent.
fn push_member_docs(docs: &[&str], out: &mut String) {
    if docs.is_empty() {
        return;
    }
    if let [only] = docs {
        out.push_str("  /** ");
        out.push_str(only);
        out.push_str(" */\n");
        return;
    }
    out.push_str("  /**\n");
    for line in docs {
        out.push_str("   * ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("  */\n");
}
