//! # bffi-core
//!
//! Foundation crate of the bffi-rs framework: native bindings for
//! [Bun](https://bun.sh) written in Rust on top of `bun:ffi` and a thin C
//! ABI (see `docs/DESIGN.md`).
//!
//! This is the bottom-most Rust layer of the stack. Every other `bffi-*`
//! crate (`bffi-types`, `bffi-error`, `bffi-object`, …) builds on the
//! primitives defined here:
//!
//! - [`handle`] - the opaque [`Handle`] and [`TypeTag`]s that cross the C
//!   ABI instead of raw Rust references;
//! - [`table`] - generational handle tables ([`HandleTable`]) that own the
//!   Rust-side objects;
//! - [`catalog`] - the process-wide [`Registry`] routing handles to typed
//!   tables by tag;
//! - [`error`] - [`ErrorCode`]s and the thread-local *last error* transport
//!   used to move failures across the C ABI;
//! - [`boundary`] - panic containment for `extern "C"` functions
//!   ([`catch_panic`], [`bffi_extern!`]).
//!
//! The C ABI layer itself (the `extern "C"` functions called from Bun) is
//! generated by `bffi-macros` / `bffi-build` (P1/P2) and *uses* this crate;
//! no `extern "C"` functions live here.
//!
//! ## Safety model
//!
//! Authoritative description: `docs/DESIGN.md` §6. In short:
//!
//! 1. **FFI boundary** - every `extern "C"` function is thin and runs its
//!    body under panic containment; panics never cross the boundary in
//!    release builds.
//! 2. **Ownership via handles** - Rust objects are stored as `Arc<T>`
//!    inside handle tables; the C ABI only ever sees opaque
//!    [`Handle`]s. Stale handles are rejected through generations.
//! 3. **Copy by default** - buffers and strings are copied across the
//!    boundary; zero-copy will be an explicit, visibly unsafe API living in
//!    `bffi-types`, not here.
//! 4. **Panics** - debug builds may let a panic abort the process (better
//!    debugging); release builds convert it into a JS `Error` via the
//!    last-error transport.
//!
//! ## Handle layout
//!
//! ```text
//! 63        48 47            24 23             0
//! ┌────────────┬────────────────┬────────────────┐
//! │  type tag  │   generation   │      index     │
//! │   16 bits  │     24 bits    │     24 bits    │
//! └────────────┴────────────────┴────────────────┘
//! ```
//!
//! ## Example
//!
//! ```
//! use std::sync::Arc;
//! use bffi::core::{HandleTable, Registry, TypeTag};
//!
//! // user modules own tags in the 0x8000–0xFFFF range
//! struct File { path: String }
//! const FILE: TypeTag = TypeTag(0x8100);
//!
//! // Per-module tables work standalone…
//! let local = HandleTable::<File>::new(TypeTag(0x8101));
//! let h = local.insert(Arc::new(File { path: "a".into() })).expect("room");
//! assert_eq!(local.get(h).unwrap().path, "a");
//!
//! // …or through the process-wide registry used by the C ABI layer.
//! let registry = Registry::global();
//! registry.declare::<File>(FILE).expect("declared once");
//! let rh = registry.insert(FILE, Arc::new(File { path: "b".into() })).expect("room");
//! assert!(registry.get_typed::<File>(rh).is_some());
//! assert!(registry.remove(rh));
//! ```
//!
//! ## Crate boundaries
//!
//! This crate deliberately contains **no** type conversion (→
//! `bffi-types`), no JS `Error` construction (→ `bffi-error`), no object
//! wrappers (→ `bffi-object`), no callback machinery (→ `bffi-callback`)
//! and no macro/build integration (→ `bffi-macros` / `bffi-build`).
//!
//! ## Implementation notes
//!
//! - Zero runtime dependencies: `std` only.
//! - **Unsafe is isolated and audited**: the handle table (lock-free cells,
//!   refcount surgery) and the SIMD string validation in `bffi-types` are
//!   the only places allowed to use `unsafe`; every block carries a
//!   `SAFETY:` justification and all public API is 100% safe.
//! - Release builds require unwinding (`panic = "unwind"`, the workspace
//!   default) so [`catch_panic`] can convert panics; abort-on-panic would
//!   kill the whole Bun host process.

// Internal module aliases (the pre-merge crate names).
// The workspace restriction lints (expect/unwrap/panic) target production
// code; tests assert invariants and intentionally trigger panics.
#![cfg_attr(test, allow(clippy::expect_used, clippy::panic, clippy::unwrap_used))]

pub mod boundary;
pub mod catalog;
pub mod error;
pub mod handle;
pub(crate) mod hazard;
pub mod table;

pub use boundary::{catch_panic, panic_message, run_extern_body, run_extern_body_or};
pub use catalog::{Registry, RegistryError};
pub use error::{BffiError, ErrorCode, ErrorRich, set_last_error, take_last_error};
pub use handle::{Handle, MAX_GENERATION, MAX_INDEX, TypeTag};
pub use table::{HandleTable, TableError};
