// @generated by bffi codegen - do not edit.
// Source module: errors

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "errors",
  "functions": [
    {
      "name": "find_user",
      "export": "bffi_find_user",
      "docs": [
        "Looks a user up by id; `NOT_FOUND` carries the id."
      ],
      "params": [
        {
          "name": "id",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "User",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "validate_age",
      "export": "bffi_validate_age",
      "docs": [
        "Validates an age; `INVALID_AGE` carries the value and the bound."
      ],
      "params": [
        {
          "name": "age",
          "ts": "number",
          "abi": "i32"
        }
      ],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "ad_hoc",
      "export": "bffi_ad_hoc",
      "docs": [
        "An ad-hoc error: a plain `String` maps to DomainError (13)."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "framework_error",
      "export": "bffi_framework_error",
      "docs": [
        "BffiError itself is a valid error type (a framework code path)."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "User",
      "docs": [
        "One user record (returned as a B1 record)."
      ],
      "fields": [
        {
          "name": "id",
          "docs": [],
          "ts": "bigint"
        },
        {
          "name": "name",
          "docs": [],
          "ts": "string"
        }
      ]
    }
  ],
  "enums": [],
  "errors": [
    {
      "name": "UsersError",
      "docs": [
        "The typed error enum of the module. Each variant carries a stable",
        "code in the reserved user range; the JS side switches on `e.code`",
        "and reads `e.name` / `e.payload`."
      ],
      "variants": [
        {
          "name": "NotFound",
          "docs": [
            "No user with the given id."
          ],
          "code": "0x1001",
          "fields": [
            {
              "name": "id",
              "docs": [
                "The queried id."
              ],
              "ts": "bigint"
            }
          ]
        },
        {
          "name": "InvalidAge",
          "docs": [
            "The age is outside the supported range."
          ],
          "code": "0x1002",
          "fields": [
            {
              "name": "age",
              "docs": [
                "The rejected value."
              ],
              "ts": "number"
            },
            {
              "name": "min",
              "docs": [
                "The lowest allowed age."
              ],
              "ts": "number"
            }
          ]
        }
      ]
    }
  ]
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
