// @generated by bffi codegen - do not edit.
// Source module: errors
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeAt,
  makeReadBuffer,
  makeTakeError,
  tablesOf,
  wireToJs,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "errors",
  "abiVersion": 1,
  "exportsHash": "11945330998765277442",
  "functions": [
    {
      "name": "find_user",
      "export": "bffi_find_user",
      "docs": [
        "Looks a user up by id; `NOT_FOUND` carries the id."
      ],
      "params": [
        {
          "name": "id",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "User",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "validate_age",
      "export": "bffi_validate_age",
      "docs": [
        "Validates an age; `INVALID_AGE` carries the value and the bound."
      ],
      "params": [
        {
          "name": "age",
          "ts": "number",
          "abi": "i32"
        }
      ],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "ad_hoc",
      "export": "bffi_ad_hoc",
      "docs": [
        "An ad-hoc error: a plain `String` maps to DomainError (13)."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "framework_error",
      "export": "bffi_framework_error",
      "docs": [
        "BffiError itself is a valid error type (a framework code path)."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [
    {
      "name": "User",
      "docs": [
        "One user record (returned as a B1 record)."
      ],
      "fields": [
        {
          "name": "id",
          "docs": [],
          "ts": "bigint"
        },
        {
          "name": "name",
          "docs": [],
          "ts": "string"
        }
      ]
    }
  ],
  "enums": [],
  "errors": [
    {
      "name": "UsersError",
      "docs": [
        "The typed error enum of the module. Each variant carries a stable",
        "code in the reserved user range; the JS side switches on `e.code`",
        "and reads `e.name` / `e.payload`."
      ],
      "variants": [
        {
          "name": "NotFound",
          "docs": [
            "No user with the given id."
          ],
          "code": "0x1001",
          "fields": [
            {
              "name": "id",
              "docs": [
                "The queried id."
              ],
              "ts": "bigint"
            }
          ]
        },
        {
          "name": "InvalidAge",
          "docs": [
            "The age is outside the supported range."
          ],
          "code": "0x1002",
          "fields": [
            {
              "name": "age",
              "docs": [
                "The rejected value."
              ],
              "ts": "number"
            },
            {
              "name": "min",
              "docs": [
                "The lowest allowed age."
              ],
              "ts": "number"
            }
          ]
        }
      ]
    }
  ]
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const tables = tablesOf(moduleJson);
  const out_find_user = new BigUint64Array(1);
  const sym_find_user = sym("bffi_find_user");
  const fn_find_user = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"User", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("find_user: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_find_user(a0, out_find_user));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_find_user failed: " + String(status));
    }
    if (typeof ((out_find_user[0] ?? 0n)) !== "bigint") {
      throw new TypeError("find_user: expected a buffer handle");
    }
    const bytes_find_user = readBuffer((out_find_user[0] ?? 0n));
    return wireToJs(tables, "User", decodeAt(bytes_find_user, 0).value, "find_user()") as TsOf<"User", typeof moduleJson>;
  };
  const out_validate_age = new Uint8Array(1);
  const sym_validate_age = sym("bffi_validate_age");
  const fn_validate_age = function (a0: TsOf<"number", typeof moduleJson>): TsOf<"boolean", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("validate_age: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_validate_age(a0, out_validate_age));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_validate_age failed: " + String(status));
    }
    return (out_validate_age[0] ?? 0) !== 0;
  };
  const sym_ad_hoc = sym("bffi_ad_hoc");
  const fn_ad_hoc = function (): void {
    if (arguments.length !== 0) {
      throw new Error("ad_hoc: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_ad_hoc());
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_ad_hoc failed: " + String(status));
    }
  };
  const sym_framework_error = sym("bffi_framework_error");
  const fn_framework_error = function (): void {
    if (arguments.length !== 0) {
      throw new Error("framework_error: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_framework_error());
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_framework_error failed: " + String(status));
    }
  };
  return {
    "find_user": fn_find_user,
    "validate_age": fn_validate_age,
    "ad_hoc": fn_ad_hoc,
    "framework_error": fn_framework_error,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
