// @generated by bffi codegen - do not edit.
// Source module: sqlite

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "sqlite",
  "functions": [
    {
      "name": "sqlite_version",
      "export": "bffi_sqlite_version",
      "docs": [
        "The SQLite engine version (sanity check for the pipeline)."
      ],
      "params": [],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "open",
      "export": "bffi_open",
      "docs": [
        "Opens (or creates) a database and returns its connection handle.",
        "Use `:memory:` for an in-memory database."
      ],
      "params": [
        {
          "name": "path",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "exec",
      "export": "bffi_exec",
      "docs": [
        "Executes one or more SQL statements (no rows returned)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "sql",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "query",
      "export": "bffi_query",
      "docs": [
        "Runs a query and returns ALL rows as a JSON array of arrays.",
        "Values are TEXT-coerced (sqlite's dynamic typing makes this",
        "lossless for text/int/real round-trips through JS strings)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "sql",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "close",
      "export": "bffi_close",
      "docs": [
        "Closes (releases) a connection handle."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
