// @generated by bffi codegen - do not edit.
// Source module: sqlite
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  decodeUtf8,
  makeReadBuffer,
  makeTakeError,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "sqlite",
  "functions": [
    {
      "name": "sqlite_version",
      "export": "bffi_sqlite_version",
      "docs": [
        "The SQLite engine version (sanity check for the pipeline)."
      ],
      "params": [],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "open",
      "export": "bffi_open",
      "docs": [
        "Opens (or creates) a database and returns its connection handle.",
        "Use `:memory:` for an in-memory database."
      ],
      "params": [
        {
          "name": "path",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "exec",
      "export": "bffi_exec",
      "docs": [
        "Executes one or more SQL statements (no rows returned)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "sql",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "query",
      "export": "bffi_query",
      "docs": [
        "Runs a query and returns ALL rows as a JSON array of arrays.",
        "Values are TEXT-coerced (sqlite's dynamic typing makes this",
        "lossless for text/int/real round-trips through JS strings)."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        },
        {
          "name": "sql",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "close",
      "export": "bffi_close",
      "docs": [
        "Closes (releases) a connection handle."
      ],
      "params": [
        {
          "name": "handle",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const readBuffer = makeReadBuffer(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const out_sqlite_version = new BigUint64Array(1);
  const sym_sqlite_version = sym("bffi_sqlite_version");
  const fn_sqlite_version = function (): TsOf<"string", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("sqlite_version: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_sqlite_version(out_sqlite_version));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_sqlite_version failed: " + String(status));
    }
    if (typeof ((out_sqlite_version[0] ?? 0n)) !== "bigint") {
      throw new TypeError("sqlite_version: expected a buffer handle");
    }
    const bytes_sqlite_version = readBuffer((out_sqlite_version[0] ?? 0n));
    return decodeUtf8(bytes_sqlite_version);
  };
  const out_open = new BigUint64Array(1);
  const sym_open = sym("bffi_open");
  const fn_open = function (a0: TsOf<"string", typeof moduleJson>): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("open: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_open(a0, out_open));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_open failed: " + String(status));
    }
    return (out_open[0] ?? 0n);
  };
  const sym_exec = sym("bffi_exec");
  const fn_exec = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): void {
    if (arguments.length !== 2) {
      throw new Error("exec: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_exec(a0, a1));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_exec failed: " + String(status));
    }
  };
  const out_query = new BigUint64Array(1);
  const sym_query = sym("bffi_query");
  const fn_query = function (a0: TsOf<"bigint", typeof moduleJson>, a1: TsOf<"string", typeof moduleJson>): TsOf<"string", typeof moduleJson> {
    if (arguments.length !== 2) {
      throw new Error("query: expected 2 argument(s), got " + arguments.length);
    }
    const status = Number(sym_query(a0, a1, out_query));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_query failed: " + String(status));
    }
    if (typeof ((out_query[0] ?? 0n)) !== "bigint") {
      throw new TypeError("query: expected a buffer handle");
    }
    const bytes_query = readBuffer((out_query[0] ?? 0n));
    return decodeUtf8(bytes_query);
  };
  const sym_close = sym("bffi_close");
  const fn_close = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("close: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_close(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_close failed: " + String(status));
    }
  };
  return {
    "sqlite_version": fn_sqlite_version,
    "open": fn_open,
    "exec": fn_exec,
    "query": fn_query,
    "close": fn_close,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
