// @generated by bffi codegen - do not edit.
// Source module: event-loop

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "event-loop",
  "functions": [
    {
      "name": "enqueue_job",
      "export": "bffi_enqueue_job",
      "docs": [
        "Puts one job on the queue: the job stores `x * 2` into the",
        "process-wide result slot when it executes (see [`last_result`]).",
        "",
        "# Errors",
        "",
        "[`LoopError`] once [`loop_stop`] has been called (sticky)."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "i64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "last_result",
      "export": "bffi_last_result",
      "docs": [
        "The value stored by the last executed job (`0` before the first)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "i64"
      },
      "out": "i64"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "Drains the queue without blocking; returns the number of jobs",
        "executed by THIS call (`0` on an empty queue). The JS side calls",
        "it in a loop (`pumpUntil` from `@z2net/bffi`) to deliver async",
        "resolutions; here it demonstrates the raw mechanics."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_pending",
      "export": "bffi_loop_pending",
      "docs": [
        "The number of jobs waiting for execution."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_executed",
      "export": "bffi_loop_executed",
      "docs": [
        "The number of jobs executed since process start, across all",
        "runners."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "marshal_status",
      "export": "bffi_marshal_status",
      "docs": [
        "Marshals one job (`x * 2` into the result slot) onto the RUNNING",
        "loop and returns the raw `ErrorCode` numeric value: `0` = accepted",
        "(the job executes on the runner thread), `12` = `WrongThread` (no",
        "runner is up). The status variant keeps the exact code observable;",
        "the last error carries the message."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "i64"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "loop_run",
      "export": "bffi_loop_run",
      "docs": [
        "Blocks the calling thread draining the queue until [`loop_stop`];",
        "returns the number of jobs executed by THIS runner. Intended for",
        "the worker thread of the e2e test."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_stop",
      "export": "bffi_loop_stop",
      "docs": [
        "Stops the loop for good (sticky): `loop_run` returns and later",
        "`enqueue_job` calls report \"the event loop has been stopped\"."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [],
  "enums": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
