// @generated by bffi codegen - do not edit.
// Source module: event-loop
// Wrapper style: specialized (hoisted symbols and out slots,
// inline argument encoding and return decoding per ABI kind).

import { dlopen } from "bun:ffi";
import {
  type ApiOf,
  ErrorCode,
  type FfiLib,
  type FfiSymbol,
  type ModuleJson,
  type TsOf,
  buildDeclarations,
  makeTakeError,
} from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "event-loop",
  "abiVersion": 1,
  "exportsHash": "17542332129403665438",
  "functions": [
    {
      "name": "enqueue_job",
      "export": "bffi_enqueue_job",
      "docs": [
        "Puts one job on the queue: the job stores `x * 2` into the",
        "process-wide result slot when it executes (see [`last_result`]).",
        "",
        "# Errors",
        "",
        "[`LoopError`] once [`loop_stop`] has been called (sticky)."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "i64"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "last_result",
      "export": "bffi_last_result",
      "docs": [
        "The value stored by the last executed job (`0` before the first)."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "i64"
      },
      "out": "i64"
    },
    {
      "name": "loop_pump",
      "export": "bffi_loop_pump",
      "docs": [
        "Drains the queue without blocking; returns the number of jobs",
        "executed by THIS call (`0` on an empty queue). The JS side calls",
        "it in a loop (`pumpUntil` from `@z2net/bffi`) to deliver async",
        "resolutions; here it demonstrates the raw mechanics."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_pending",
      "export": "bffi_loop_pending",
      "docs": [
        "The number of jobs waiting for execution."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_executed",
      "export": "bffi_loop_executed",
      "docs": [
        "The number of jobs executed since process start, across all",
        "runners."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "marshal_status",
      "export": "bffi_marshal_status",
      "docs": [
        "Marshals one job (`x * 2` into the result slot) onto the RUNNING",
        "loop and returns the raw `ErrorCode` numeric value: `0` = accepted",
        "(the job executes on the runner thread), `12` = `WrongThread` (no",
        "runner is up). The status variant keeps the exact code observable;",
        "the last error carries the message."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "i64"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "loop_run",
      "export": "bffi_loop_run",
      "docs": [
        "Blocks the calling thread draining the queue until [`loop_stop`];",
        "returns the number of jobs executed by THIS runner. Intended for",
        "the worker thread of the e2e test."
      ],
      "params": [],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "loop_stop",
      "export": "bffi_loop_stop",
      "docs": [
        "Stops the loop for good (sticky): `loop_run` returns and later",
        "`enqueue_job` calls report \"the event loop has been stopped\"."
      ],
      "params": [],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    }
  ],
  "classes": [],
  "records": [],
  "enums": [],
  "errors": []
} as const satisfies ModuleJson;

/** The explicit low-level loader: opens the native library at
 * `libraryPath` and returns the typed API. Passing a raw binary
 * path is a trust decision - the pipeline resolves platform
 * packages by default. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  const lib: FfiLib = dlopen(libraryPath, buildDeclarations(moduleJson)).symbols as FfiLib;
  const takeError = makeTakeError(lib);
  const sym = (name: string): FfiSymbol => {
    const found = lib[name];
    if (typeof found !== "function") {
      throw new Error("missing export: " + name);
    }
    return found;
  };
  const sym_enqueue_job = sym("bffi_enqueue_job");
  const fn_enqueue_job = function (a0: TsOf<"bigint", typeof moduleJson>): void {
    if (arguments.length !== 1) {
      throw new Error("enqueue_job: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_enqueue_job(a0));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_enqueue_job failed: " + String(status));
    }
  };
  const out_last_result = new BigInt64Array(1);
  const sym_last_result = sym("bffi_last_result");
  const fn_last_result = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("last_result: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_last_result(out_last_result));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_last_result failed: " + String(status));
    }
    return (out_last_result[0] ?? 0n);
  };
  const out_loop_pump = new BigUint64Array(1);
  const sym_loop_pump = sym("bffi_loop_pump");
  const fn_loop_pump = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pump: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pump(out_loop_pump));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pump failed: " + String(status));
    }
    return (out_loop_pump[0] ?? 0n);
  };
  const out_loop_pending = new BigUint64Array(1);
  const sym_loop_pending = sym("bffi_loop_pending");
  const fn_loop_pending = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_pending: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_pending(out_loop_pending));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_pending failed: " + String(status));
    }
    return (out_loop_pending[0] ?? 0n);
  };
  const out_loop_executed = new BigUint64Array(1);
  const sym_loop_executed = sym("bffi_loop_executed");
  const fn_loop_executed = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_executed: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_executed(out_loop_executed));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_executed failed: " + String(status));
    }
    return (out_loop_executed[0] ?? 0n);
  };
  const out_marshal_status = new Uint32Array(1);
  const sym_marshal_status = sym("bffi_marshal_status");
  const fn_marshal_status = function (a0: TsOf<"bigint", typeof moduleJson>): TsOf<"number", typeof moduleJson> {
    if (arguments.length !== 1) {
      throw new Error("marshal_status: expected 1 argument(s), got " + arguments.length);
    }
    const status = Number(sym_marshal_status(a0, out_marshal_status));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_marshal_status failed: " + String(status));
    }
    return (out_marshal_status[0] ?? 0);
  };
  const out_loop_run = new BigUint64Array(1);
  const sym_loop_run = sym("bffi_loop_run");
  const fn_loop_run = function (): TsOf<"bigint", typeof moduleJson> {
    if (arguments.length !== 0) {
      throw new Error("loop_run: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_run(out_loop_run));
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_run failed: " + String(status));
    }
    return (out_loop_run[0] ?? 0n);
  };
  const sym_loop_stop = sym("bffi_loop_stop");
  const fn_loop_stop = function (): void {
    if (arguments.length !== 0) {
      throw new Error("loop_stop: expected 0 argument(s), got " + arguments.length);
    }
    const status = Number(sym_loop_stop());
    if (status !== ErrorCode.Ok) {
      const error = takeError(status);
      throw error ?? new Error("bffi_loop_stop failed: " + String(status));
    }
  };
  return {
    "enqueue_job": fn_enqueue_job,
    "last_result": fn_last_result,
    "loop_pump": fn_loop_pump,
    "loop_pending": fn_loop_pending,
    "loop_executed": fn_loop_executed,
    "marshal_status": fn_marshal_status,
    "loop_run": fn_loop_run,
    "loop_stop": fn_loop_stop,
  };
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
